### ISSUE TITLE
Nested MetricCollection

### ISSUE THREAD

**Issue by tsteffek** [PyTorchLightning/metrics#1000]
## 🚀 Feature

Allowing MetricCollection to contain other MetricCollections for even less boilerplate and coding effort.

### Motivation

When using both micro and macro metrics I either need to call two different collections or provide the collection with a dictionary of names, which could easily be created by appending a post-/prefix to the metric name.

### Pitch

I envision something like:
```python
metrics = MetricCollection([
    MetricCollection([
        StatScores(reduce='macro'),
        F1Score(reduce='macro')
    ], postfix='_macro'),
    MetricCollection([
        StatScores(reduce='micro'),
        F1Score(reduce='micro')
    ], postfix='_micro'),
], prefix='valmetrics/')
```

I want a nested collection to be treated like any other metric. Ideally nested collections would also make use of `compute_groups`.

### Alternatives

The same functionality can already be achieved by:

```python
metrics = MetricCollection({
    'statscores_macro': StatScores(reduce='macro'),
    'f1_macro': F1Score(reduce='macro'),
    'statscores_micro': StatScores(reduce='micro'),
    'f1_micro': F1Score(reduce='micro')
}, prefix='valmetrics/')
```

But I think accepting nested collections would make for a more convenient interface.
(It would probably be the easiest solution to just generate this version if presented with nested collections.)

**Comment by SkafteNicki** [comment]
cc: @Borda and @justusschock 
Seems like a good idea to me, but it will not work with the compute group feature we just implemented.
