### ISSUE TITLE
KL-Divergence gives NaN on 0-probabilities

### ISSUE THREAD

**Issue by thomasahle** [PyTorchLightning/metrics#1029]
## 🐛 Bug

KL-Divergence defined `sum_i p_i log(p_i / q_i)` should allow `p_i`s to be zero, simply ignoring those terms. This is standard behavior, similar to how entropy `sum_i p_i log(1/p_i)` can be computed with some `p_i`s being zero.
(Note `q_i`s should not be allowed 0, unless the corresponding p_i also is.)

#### Code sample

```
>>> kl = torchmetrics.KLDivergence()
>>> kl.update(torch.tensor([1,0,0],[1,0,0],[0,0,1]]), torch.tensor(torch.randn(3,3).softmax(dim=-1)))
>>> kl.compute()
tensor(nan)
```

### Expected behavior

Some value other than `nan`.

### Environment

- torchmetrics==0.8.2

### Additional context

Allowing 0 values also makes it easier to use KL-Divergence to compute NLL scores. Similar to how Brier scores can be computed using MeanSquaredError on one-hot vectors.

**Comment by SkafteNicki** [comment]
Hi @thomasahle 
I created PR #1030 which will solve this problem. Thanks for reporting this issue.

**Comment by thomasahle** [comment]
You should try this test too: p=[0.5, 0.5, 0], q=[0.5, 0.5, 0], which should work without problems.
And maybe p=[0.3, 0.3, 0.4], q=[0.5, 0.5, 0] which should ideally return inf (not nan)
