### ISSUE TITLE
Include AverageMeter?

### ISSUE THREAD

**Issue by alanhdu** [PyTorchLightning/metrics#129]
One common pattern I've seen copy-pasted across many different projects is a generic `AverageMeter`, which takes the average of things of a quantity. 

This isn't strictly a "metric", but I'm wondering whether you'd be open to having an implementation in this metrics repository -- it's quite common and having it in a centralized place could be helpful. If you are open to it, I'd be happy to contribute an implementation.

```python
class AverageMeter(object):
    """Computes and stores the average and current value"""

    def __init__(self, name, fmt=':f'):
        self.name = name
        self.fmt = fmt
        self.reset()

    def reset(self):
        self.val = 0.
        self.avg = 0.
        self.sum = 0.0
        self.count = 0

    def update(self, val, n=1):
        self.val = float(val.item()) if isinstance(
            val, (np.ndarray, torch.Tensor)) else val
        self.sum += val * n
        self.count += n
        self.avg = self.sum / self.count

    def __str__(self):
        fmtstr = '{name} {val' + self.fmt + '} ({avg' + self.fmt + '})'
        return fmtstr.format(**self.__dict__)
```

**Comment by SkafteNicki** [comment]
@alanhdu I think it is a great addition to torchmetrics. 
We would still need it to fit into the general `torchmetrics` layout meaning that it should inherent from `torchmetrics.Metric` and implement both a `update` and `compute` method.
