### ISSUE TITLE
Implement __getitem__ as "metric arithmetic"

### ISSUE THREAD

**Issue by victorjoos** [PyTorchLightning/metrics#132]
## 🚀 Feature

Allow a user to define a new metric that takes an item out of an other metric.

Basically :

```python
iou = IoU(num_classes=2, reduction="none")
fg_iou = iou[0]
bg_iou = iou[1]
```

### Motivation

There are multiple metrics (like IoU and confusion matrix) that would benefit from the use of such a feature, and it is close to the mechanism of metric arithmetic.

### Pitch

This would only need to define 
```python
class Metric:
    ...
    def __getitem__(self, idx):
        return CompositionalMetric(lambda x: x[idx], self, None)
```

### Alternatives

The straightforward alternative is to use CompositionalMetric directly.

**Comment by SkafteNicki** [comment]
@justusschock
