### ISSUE TITLE
Improve test utilities to accept metrics with more input arguments

### ISSUE THREAD

**Issue by lucadiliello** [PyTorchLightning/metrics#136]
## 🚀 Feature
Improve test utilities to accept metrics with a variable number of arguments (at the moment only 2 args are allowed).

### Motivation

At the moment the test utilities accept only 2 arguments in input: `preds` and `target`. Some metrics, like `RetrievalMAP` and `RetrievalMRR` require a different number of arguments.

**Comment by jspaezp** [comment]
I can give it a go (I am working on adding spatial metrics and have to deal with this anyway...)

Nonetheless I had a couple of questions...
 1. should it support named arguments and positional matching or only one of those?
 2. should it support different matchings between the reference metric and the implemented metric? (let me know if this makes sense ...)

**Comment by lucadiliello** [comment]
> I can give it a go (I am working on adding spatial metrics and have to deal with this anyway...)
> 
> Nonetheless I had a couple of questions...
> 
> 1. should it support named arguments and positional matching or only one of those?
> 2. should it support different matchings between the reference metric and the implemented metric? (let me know if this makes sense ...)

I think it would be better to allow both arguments types. But let's hear the opinion of @Borda and @SkafteNicki. For the second question, I do not know.

**Comment by SkafteNicki** [comment]
I think the proposal solution @jspaezp has implemented is fine. Atleast, it will cover our needs right now. We can always add support for more whenever the case may be.
