### ISSUE TITLE
MetricCollection should enforce order when passed a dict

### ISSUE THREAD

**Issue by maximsch2** [PyTorchLightning/metrics#159]
## 🐛 Bug

Not a clear bug yet, but just thinking about distributed metric computation, in here: https://github.com/PyTorchLightning/metrics/blob/53d570158a503497351ae45ec895ca44a0546068/torchmetrics/collections.py#L81
we should make sure to sort the names before the insert so that we insert things in the same order (ModuleDict is already OrderedDict otherwise). If we don't we will get deadlocks when doing distributed metric updates.

Additionally, we might want to enforce sorting when passed list/tuple, but that might be more on the user end.

### To Reproduce

On each of the workers, pass dictionary with same metrics but in different order, try compute and observe deadlock.

**Comment by SkafteNicki** [comment]
I agree that this should make the it more robust.
I think the only reason we have not seen this as a problem before, is that you explicit need to construct it in a different order on each process.

**Comment by SkafteNicki** [comment]
@maximsch2 after thinking a bit more about this, is it just an artificially problem?
You need to explicit create a different order dependent on the rank of the process for this to be a trouble.

**Comment by maximsch2** [comment]
I think it's not super easy issue to trigger with simple code, but if you have a framework that wraps your code and constructs metric collections, then things can go weird. Given that it's pretty simple problem to solve, I think it's worth it to be defensive here. Let me just send a PR actually.
