### ISSUE TITLE
Tensor device configuration bug

### ISSUE THREAD

**Issue by Yuejiang-li** [PyTorchLightning/metrics#167]
I found that when calculating accuracy, there are some temporary variables created without indicating the device.

In `accuracy.py` - [line121](https://github.com/PyTorchLightning/metrics/blob/a17ccb23d31942e920bf1ecb420382a17911e4cd/torchmetrics/classification/accuracy.py#L121), the member tensor `self.correct` and `self.total` are created without indicating the device.

If this is an expected behavior, I think there should exist some hints in readme docs, telling users to shift predictions and targets from gpu to cpu before using metrics functions.

In addition, other metrics like recall, precision, f1, may encounter similar situation (see `stat_scores.py`-[line197](https://github.com/PyTorchLightning/metrics/blob/a17ccb23d31942e920bf1ecb420382a17911e4cd/torchmetrics/classification/stat_scores.py#L197), `conf_matrix.py`-[line119](https://github.com/PyTorchLightning/metrics/blob/a17ccb23d31942e920bf1ecb420382a17911e4cd/torchmetrics/classification/confusion_matrix.py#L119))

### To Reproduce
One can simply enters the following codes:
```Python
>>> import torch
>>> from torchmetrics import Accuracy
>>> a = torch.randint(3, size=(10,), device=cuda0)
>>> b = torch.randint(3, size=(10,), device=cuda0)
>>> accuracy = Accuracy()
>>> accuracy(a, b)
```

Then, one can obtain the following error:
```Python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path>/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<path>/lib/python3.8/site-packages/torchmetrics/metric.py", line 152, in forward
    self.update(*args, **kwargs)
  File "<path>/lib/python3.8/site-packages/torchmetrics/metric.py", line 199, in wrapped_func
    return update(*args, **kwargs)
  File "<path>/lib/python3.8/site-packages/torchmetrics/classification/accuracy.py", line 142, in update
    self.correct += correct
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

 - PyTorch Version: 1.8.1
 - Torchmetrics Version: 0.2.0
 - OS: Linux
 - How you installed PyTorch (`conda`, `pip`, source): `conda`
 - Python version: 3.8.5

**Comment by Borda** [comment]
@Yuejiang-li mind check latest `v0..3.0rc`?

**Comment by Yuejiang-li** [comment]
> @Yuejiang-li mind check latest `v0..3.0rc`?

Sure, and the issue still exists.

**Comment by Borda** [comment]
@Yuejiang-li interested in sending out a fix? 🐰

**Comment by Yuejiang-li** [comment]
> @Yuejiang-li interested in sending out a fix? 🐰

My pleasure. A new pull request?

**Comment by maximsch2** [comment]
I think the reason for this is that usual workflow/tests are assuming we keep the metric on the same LightingModule that produces the predictions, so scores/predictions and the metric are always on the same device and you don't need to do any moves manually.

It does make sense for all metrics to take `device` argument as well though for ad-hoc cases like this.

**Comment by Yuejiang-li** [comment]
> I think the reason for this is that usual workflow/tests are assuming we keep the metric on the same LightingModule that produces the predictions, so scores/predictions and the metric are always on the same device and you don't need to do any moves manually.
> 
> It does make sense for all metrics to take `device` argument as well though for ad-hoc cases like this.

Aha, I did forget that! Transferring the metric instance to gpu ahead can solve this issue. Thanks @maximsch2 .

@Borda Seems like there is no need to fix this "bug"?

**Comment by justusschock** [comment]
@maximsch2 IMO, when you want a different device, couldn't you just do `metric.to(device)` independently of the module?

**Comment by Yuejiang-li** [comment]
> @maximsch2 IMO, when you want a different device, couldn't you just do `metric.to(device)` independently of the module?

Yes, I actually solved this problem by transferring metric first.

**Comment by SkafteNicki** [comment]
Please also see this part of the documentation: https://torchmetrics.readthedocs.io/en/latest/pages/overview.html#metrics-and-devices
Closing as issue seems resolved.
