### ISSUE TITLE
Add support for the FID metric.

### ISSUE THREAD

**Issue by ohayonguy** [PyTorchLightning/metrics#169]
## 🚀 Feature
Add support for the Frechet Inception Distance as a metric, to evaluate generative models (https://arxiv.org/abs/1706.08500)

### Motivation
This metric is used in many recent GAN applications to evaluate the perceptual quality of the generated images.
It is therefore a very helpful and important metric to implement.

### Alternatives
The inception score could be also used as well, but FID is more acceptable today.

**Comment by Borda** [comment]
@ohayonguy are you interested in implementing it?
closing this one in favor of #65 lets continue discussion there...
