### ISSUE TITLE
Can't import the metric straight away

### ISSUE THREAD

**Issue by ncuxomun** [PyTorchLightning/metrics#179]
## 🐛 Bug

Not able to import Pearson and Spearman coefficient metrics.

### To Reproduce

1. Go to website example
2. Run from torchmetrics import PearsonCorrcoef
3. See error

ImportError: cannot import name 'PearsonCorrcoef' from 'torchmetrics' (C:\Users\ulugb\AppData\Local\Programs\Python\Python39\lib\site-packages\torchmetrics\__init__.py)

### Environment

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.9.2
 - CUDA/cuDNN version: -
 - GPU models and configuration: - 
 - Any other relevant information: -

**Comment by SkafteNicki** [comment]
`PearsonCorrcoef` is still not officially released, but will definitely be part of the 0.3.0 release (which is going to be released any time soon).
If you want access right now, please install directly from master
```pip install git+https://github.com/PytorchLightning/metrics.git@master```
