### ISSUE TITLE
Metrics are on another divice when create with __dict__ inside pl.LightningModule

### ISSUE THREAD

**Issue by IgorHoholko** [PyTorchLightning/metrics#181]
### To Reproduce

1. Create an accuracy object in any file (metrics.py) `accuracy  = Accuracy( compute_on_step=False)`  {or any other metric}
2. `import metrics`
3. inside your `class BaseLitModel(pl.LightningModule)` set the metric
`self.__dict__[f'train_{metric_name}'] = getattr(metrics, metric_name)`
4. When call `self.__dict__[metric_key](logits, y)` get Error, that different devices in Metrics and Model.

So it is interesting what is difference between when you create the metrics directly in the model class, and when you import ready metric object from outside and write it directly to **self**. Why in the second case it won't be moved on the model's device. 

#### Code sample

**metrics.py**

```
from torchmetrics.classification import (Accuracy, Precision, Recall, AveragePrecision, F1, AUROC)

# Classification
accuracy =          Accuracy( compute_on_step=False)
accuracy_weighted = Accuracy( average='weighted', compute_on_step=False,  num_classes=3)
accuracy_macro =    Accuracy(average='macro', compute_on_step=False, num_classes=3)
```

**model.py**
``` 
class BaseLitModel(pl.LightningModule):  

    def __init__(self, model, args: argparse.Namespace = None):
        super().__init__()
        self.model = model
        self.args = vars(args) if args is not None else {}

        optimizer = self.args.get("optimizer", OPTIMIZER)
        self.optimizer_class = getattr(torch.optim, optimizer)

        self.lr = self.args.get("lr", LR)
        self.metrics = self.args.get("metrics", METRICS)

        loss = self.args.get("loss", LOSS)
        self.loss_fn = getattr(torch.nn.functional, loss)


        for metric_name in self.metrics:
            self.__dict__[f'train_{metric_name}'] = getattr(metrics, metric_name).to(self.device)
            self.__dict__[f'val_{metric_name}'] = getattr(metrics, metric_name).to(self.device)
            self.__dict__[f'test_{metric_name}'] = getattr(metrics, metric_name).to(self.device)

    def training_step(self, batch, batch_idx):  # pylint: disable=unused-argument
        x, y = batch['image'], batch['label']
        out = self(x)
        logits = torch.nn.functional.softmax(out, dim=-1)

        loss = self.loss_fn(logits, y)
        for metric_name in self.metrics:
            metric_key = f'train_{metric_name}'
            self.__dict__[metric_key](logits, y)
            self.log(metric_key, self.__dict__[metric_key], on_step=False, on_epoch=True)
        self.log("train_loss", loss)

        return {'loss':loss, 'y':y, 'logits': logits}
```

### Expected behavior

`self.tp += tp
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

### Environment
 - python3.7
 - torchmetrics==0.3.0
 - pytorch-lightning==1.2.7
 - torch==1.8.1
 - Ubuntu 18

**Comment by SkafteNicki** [comment]
This is a general limitation with any Pytorch module, that any submodule needs to be correctly identified as a child module if you want it to move to the correct device when moving the hole module. Take this small example:
``` python
from torch import nn
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.__dict__['something'] = nn.Linear(10,10)

m = MyModel()
print(list(m.children())) # prints []
```
therefore `self.__dict__` cannot be used. It is also explained in this part of the documentation:
https://torchmetrics.readthedocs.io/en/latest/pages/overview.html#metrics-and-devices

**Comment by IgorHoholko** [comment]
Thank you @SkafteNicki.
MetricCollection is what I needed.
