### ISSUE TITLE
Precision Metric based on Quantiles

### ISSUE THREAD

**Issue by GeorgWa** [PyTorchLightning/metrics#183]
## 🚀 Feature
The precision is only calculated for the selected Quantile (top 1%, top 5% etc..) of every class.

### Motivation

Im working on ML Classifiers for CRISPR/Cas9 screens and we screen millions of cells to find a subset (for example 1%, 0.1%) which shows a highly enriched feature. As the base rate of the feature may be very low compared to all other features, the false positive rate needs to be as low as possible. Luckily, due to the high throughput, we are able to focus on a subset of all positive predictions with the highest precision. Therefore, precision of some top quantile is a valuable metric for us.

### Pitch

I am implementing this metric anyways and would propose to include it with the other metrics if you think its a fit.

### Alternatives

It could be integrated as standalone metric or be included in the Precision metric.

### Additional context

Please feel free to reach out and discuss this :)

**Comment by Borda** [comment]
@GeorgWa that sounds nice tom, would you be interested in implementing this enhancement? :rabbit:

**Comment by GeorgWa** [comment]
Yes, i would implement it myself first and then we can look how to merge it. My question is if i should implement it as standalone metric or as extension of the precision metric?

**Comment by Borda** [comment]
I would think about the extension of exiting... let's open a draft PR as soon as you are ready to have a discussion about it :rabbit: 
cc: @SkafteNicki

**Comment by GeorgWa** [comment]
Okay, great 👍

**Comment by SkafteNicki** [comment]
@GeorgWa if you could provide basic implementation of what this feature involves (just on the precision metric), then we can figure out if it can be extended into something general.
IMO it would be great if it worked like the new bootstrapping wrapper metric: https://torchmetrics.readthedocs.io/en/latest/references/modules.html#wrappers
