### ISSUE TITLE
F1 Function Error

### ISSUE THREAD

**Issue by oggyfaker** [PyTorchLightning/metrics#185]
Hi authors ! I have some issue with F1 function in torchmetrics. When i use:
```
torchmetrics.F1(num_classes = self.num_classes, average='weighted', multilabel=True)
```
It works !! But i have warning :  UserWarning: The `multilabel=True` parameter is unused and will not have any effect.

And then i changed `torchmetrics.F1(num_classes = self.num_classes, average='weighted', multilclass=True)` like the documment : https://torchmetrics.readthedocs.io/en/latest/references/modules.html#f1. 
I have the error with init :  `TypeError: __init__()` got an unexpected keyword argument 'multiclass'

So what should i do to solve this issue ? Thanks and hope for your answer !

**Comment by Borda** [comment]
@oggyfaker what version are you using? The `multiclass was added din latest RC version so most likely you give installed v0.2.0 https://torchmetrics.readthedocs.io/en/stable/references/modules.html#f1

**Comment by oggyfaker** [comment]
Yes, I am using the lastet version ![image](https://user-images.githubusercontent.com/44501897/115235270-32f99e80-a144-11eb-9e22-c73c405b159e.png).

**Comment by SkafteNicki** [comment]
You need to install directly from master to get the latest changes (or wait until v0.3 drops which is soon)
```
pip install git+https://github.com/PytorchLightning/metrics.git@master
```

**Comment by Borda** [comment]
you can also install the last RC as `pip install torchmetrics==0.3.0rc1`

**Comment by oggyfaker** [comment]
Thanks for your answer. The issue of multi class parameter solved. But it raised the new error with num_classes:
 >> ValueError: Your have set `multiclass=True`, but `num_classes` is not equal to 2. If you are trying to transform multi-label data to 2 class multi-dimensional multi-class, you should set `num_classes` to either 2 or None.
I just turned off the raise error function but it still error with 
![image](https://user-images.githubusercontent.com/44501897/115248101-950cd080-a151-11eb-8a2c-3e3254775f07.png)
So what should i do ? Hope to see your answer soon !

**Comment by SkafteNicki** [comment]
@oggyfaker could you please tell me what your data looks like, just to make sure that I can answer correctly.

**Comment by oggyfaker** [comment]
> @oggyfaker could you please tell me what your data looks like, just to make sure that I can answer correctly.
My dataloader will return like this ! 
![image](https://user-images.githubusercontent.com/44501897/115597906-012f3600-a304-11eb-907c-07d0e74a7d22.png)
