### ISSUE TITLE
Allow general pickle-able types as state objects?

### ISSUE THREAD

**Issue by christopherbate** [PyTorchLightning/metrics#190]
## 🚀 Feature + Motivation
Some types of metrics, such as "COCO detection metrics" for computer vision are more easily computed by operating on lists of dictionaries containing arrays rather than pure tensors. In this case, the developer would like to keep multiple pieces of information about each prediction, such as the example ID, bounding boxes and associated scores, etc. I recently wrote a `torchmetrics` wrapper for COCO API metrics, but it was made more complicated by requiring the state objects to be tensors. It would be trivial if I could keep a list of dictionaries as the state object. Synchronization in Torch >= 1.8.0 can be done easily via `all_gather_objects` but for < 1.8.0 requires some pickling into a Tensor hack.

### Pitch

Allow state objects to have lists of pickle-able objects.

### Alternatives

Without this, I need to keep several state objects broken out by the sub-keys of my dictionary. It's not necessarily difficult but it is more code.

I can probably help do this unless someone can point out why it's too difficult/impossible. I still need to dig into the source a bit more.

**Comment by zhiqwang** [comment]
Hi @christopherbate ,

torchvision before have released a pickle-able version `all_gather` [here](https://github.com/pytorch/vision/blob/23a67b3fe86861b03aeb8bed4c2a927949b2f740/references/detection/utils.py#L75). 

BTW I've also written a torchmetrics `wrapper` for COCO API metrics [here](https://github.com/zhiqwang/yolov5-rt-stack/blob/999fcb20fb968910440fa0e87e660cf9c55cf050/yolort/data/coco_eval.py#L28) on the basis of torchvision. But I didn't test the distributed mode, and additional checks and further encapsulation are needed here.

**Comment by SkafteNicki** [comment]
Hi @christopherbate,
I would be fine with this improvement :]
To make it easy we can enforce that anything other than empty list and tensors are only allowed if you have pytorch v1.8 or higher.

**Comment by christopherbate** [comment]
> Hi @christopherbate ,
> 
> torchvision have also added a `all_gather` on arbitrary picklable data [here](https://github.com/pytorch/vision/blob/23a67b3fe86861b03aeb8bed4c2a927949b2f740/references/detection/utils.py#L75) that supporting lower version PyTorch.
> 
> BTW I've also written a quick torchmetrics `wrapper` for COCO API metrics [here](https://github.com/zhiqwang/yolov5-rt-stack/blob/999fcb20fb968910440fa0e87e660cf9c55cf050/yolort/data/coco_eval.py#L28) based on torchvision's [CocoEvaluator](https://github.com/pytorch/vision/blob/23a67b3fe86861b03aeb8bed4c2a927949b2f740/references/detection/coco_eval.py#L19). But I didn't test the distributed mode, and additional checks and further encapsulation are needed here.

That's interesting, thanks.
I used detectron2's implementation as a reference since I'm more familiar with their API and trust its distributed implementation.

Regarding the `all_gather` operation, then, it should be easy enough to borrow that one method from torchvision, thanks for pointing that out.
