### ISSUE TITLE
Distribute + package type hints 

### ISSUE THREAD

**Issue by alanhdu** [PyTorchLightning/metrics#201]
## 🚀 Feature

Right now, `torchmetrics` mostly uses type hints for internal testing. However, these type annotations are not packaged for type checkers to consume downstream. From [PEP 561](https://www.python.org/dev/peps/pep-0561/):

> Package maintainers who wish to support type checking of their code MUST add a marker file named py.typed to their package supporting typing. 

Without this marker file, my IDE takes advantage of these type annotations, but `mypy` makes thinks everything from `torchmetrics` has an `Any` type. 

I believe the solution is to just create an empty `py.typed` file and add it to the `setup.py` (as specified https://www.python.org/dev/peps/pep-0561/#packaging-type-information) -- that is, if we think the type annotations in `torchmetrics` are "ready" to be relied on.

**Comment by Borda** [comment]
yeah we did the same for PL, mind send PR here too? :]
