### ISSUE TITLE
Cannot calculate AUROC for dummy multi-label data

### ISSUE THREAD

**Issue by fColangelo** [PyTorchLightning/metrics#205]
## 🐛 Bug

I'm trying to calculate the AUROC metric with a simple set of multi-label data to better understand the metric. 
I created some data according to the documentation (binary target and float pred with the same shape).
However, while all other metrics work fine, for AUROC I get:
```
ValueError: No negative samples in targets, false positive value should be meaningless
```
Probably this is just me misunderstanding something but I cannot find anything in the documentation justyfing this error.

#### Code sample

```
import torch
from torchmetrics import Precision, Recall, F1, MetricCollection, AveragePrecision, AUROC

target = torch.tensor([[1, 1, 0, 0], [1, 0, 0, 1]])
pred = torch.tensor([[0.9, 0.7, 0, 0], [0, 0, 0, 0.9]])
n_classes = 4
t = 0.5
metric_collection  = MetricCollection({
            "Macro_precision": Precision(num_classes=n_classes, threshold=t, average="macro"),
            "Micro_precision": Precision(num_classes=n_classes, threshold=t, average="micro"),
            "Micro_recall": Recall(num_classes=n_classes, threshold=t, average="micro"),
            "Macro_recall": Recall(num_classes=n_classes, threshold=t, average="macro"),
            "Macro_F1": F1(num_classes=n_classes, threshold=t, average="macro"),
            "Micro_F1": F1(num_classes=n_classes, threshold=t, average="micro"),
            "AUROC_Macro": AUROC(num_classes=n_classes),
            "Average_Precision": AveragePrecision(num_classes=n_classes)
        }) 
```

### Expected behavior

Obtaining the AUROC value without errors

### Environment

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Ubuntu 18
 - How you installed PyTorch (`conda`, `pip`, source): pip 
 - Build command you used (if compiling from source): -
 - Python version: 3.6.9
 - CUDA version: 10.2 
 - GPU models and configuration: Nvidia V100
 - Any other relevant information:

**Comment by SkafteNicki** [comment]
Hi @fColangelo, what version of `torchmetrics` are you using?

**Comment by fColangelo** [comment]
Hi @SkafteNicki and thank you for your answer! I'm running torchmetrics 0.2.0 for compatibility with pytorch lightning 1.2.10, sorry for forgetting to mention it sooner.

**Comment by SkafteNicki** [comment]
We have based our implementation on the `roc_auc_score` implementation from `sklearn` and for this case, that implementation will give you this error:
```ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.```
which is the same as the `false positive value ` being meaningless. Essentially, your target tensor
```python
tensor([[1, 1, 0, 0],
           [1, 0, 0, 1]])
```
in the first column does not contain any negative samples, and the third column does not contain any positive samples. AUROC metric only makes sense to calculate when both are present.

**Comment by fColangelo** [comment]
Oh, I see. Thanks for the clarification and sorry for the dumb question!

**Comment by SkafteNicki** [comment]
@fColangelo no questions are stupid :]
If you have any suggestions on how to improve the documentation, please feel free to send a PR
