### ISSUE TITLE
Reset of ConfusionMatrix doesn't reset the output of compute()

### ISSUE THREAD

**Issue by teufelweich** [PyTorchLightning/metrics#237]
## 🐛 Bug
When a ConfusionMatrix instance that has already been updated is reset, it still returns the old values before the reset.

### To Reproduce

```python
>>> torch.__version__
'1.8.0'
>>> torchmetrics.__version__
'0.2.0'
```

#### Code sample

```python
>>> import torch
>>> from torchmetrics import ConfusionMatrix
>>> target = torch.tensor([1, 1, 0, 0])
>>> preds = torch.tensor([0, 1, 0, 0])
>>> cm = ConfusionMatrix(num_classes=2)
>>> cm.compute()
tensor([[0., 0.],
        [0., 0.]])
>>> cm.update(preds, target)
>>> cm.compute()
tensor([[2., 0.],
        [1., 1.]])
>>> cm.reset()
>>> cm.compute()
tensor([[2., 0.],
        [1., 1.]])
>>> cm.confmat
tensor([[0., 0.],
        [0., 0.]])
```

### Expected behavior

The output of `cm.compute()` should be all zeros after `cm.reset()` was called.

### Environment

 - PyTorch Version (e.g., 1.0): 1.8.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.8.8

**Comment by Borda** [comment]
@teufelweich mind check latest v0.3.1 or eventually master?

**Comment by teufelweich** [comment]
Installed the archived master (`0.4.0dev`) with pip.
The first `compute()` now gives a warning, that it was was never updated previously.
After `reset()` the `compute()` works as expected and returns all zeros.

Sorry for not checking the newest version right away 😅
