### ISSUE TITLE
Error in _precision_recall_curve_update for binary classification

### ISSUE THREAD

**Issue by ZeyuSun** [PyTorchLightning/metrics#263]
## 🐛 Bug

In _precision_recall_curve_update, it should be acceptable to pass `num_classes=2` for a binary problem. However, passing `num_classes=2` raise an exception because of these lines:

https://github.com/PyTorchLightning/metrics/blob/f58f4d421d749d3bb7d2fe96c96efabd01b269c7/torchmetrics/functional/classification/precision_recall_curve.py#L79-L86

### To Reproduce

See the code sample.

#### Code sample

```python
import torch
from torchmetrics.functional.classification import roc
 
y_true = torch.tensor([0, 1, 1, 1])
y_prob = torch.tensor([0.1, 0.2, 0.5, 0.7])
fpr, tpr, thresholds = roc(y_prob, y_true, num_classes=2)
```
### Environment

 - PyTorch Version (e.g., 1.0): 1.8.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): pip install -e .
 - Python version: 3.8.8
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration: 
 - Any other relevant information:

**Comment by SkafteNicki** [comment]
Hi @ZeyuSun, the documentation directly states that you should not supply `num_classes` if you are doing binary evaluation.
https://github.com/PyTorchLightning/metrics/blob/f58f4d421d749d3bb7d2fe96c96efabd01b269c7/torchmetrics/functional/classification/precision_recall_curve.py#L176-L177

**Comment by ZeyuSun** [comment]
I see. But this kind of seems counter-intuitive. If it has to be implemented that way, then would it be better if we explicitly states that in the doc? "Not necessary" is sort of ambuiguous.
