### ISSUE TITLE
Exclude thresholds of 0.0 and 1.0 in precision recall curve

### ISSUE THREAD

**Issue by jacanchaplais** [PyTorchLightning/metrics#265]
## 🚀 Feature

Instead of using threshold values in the inclusive range [0, 1], it would be good to have (at least the option for) thresholds in the exclusive range (0, 1). Custom threshold values would be even better, in my opinion.

### Motivation

I am tracking metrics for memory intensive models, and don't want to keep track of values which are not useful. Also, it clutters up my TensorBoard, which is mildly annoying.

### Pitch

I guess you could just add in an optional boolean argument like
```python
def BinnedPrecisionRecallCurve(..., exclusive: bool = False):
    ...
```
to exclude the edge values.

### Alternatives

If you wanted to allow user specified thresholds, which I would prefer but might be confusing with "binned" being part of the name, perhaps you could allow:
```python
pr = BinnedPrecisionRecallCurve(num_thresholds=None, thresholds=[0.1, 0.5, 0.9], ...)
```

**Comment by SkafteNicki** [comment]
@maximsch2 any opinion here?
