### ISSUE TITLE
Incorrect results with ignore_index in IoU

### ISSUE THREAD

**Issue by CSautier** [PyTorchLightning/metrics#312]
## 🐛 Bug

The ignore_index option in IoU does not behave as it should

### To Reproduce

Run the above code

#### Code sample

```python
import torch
import torchmetrics

iou = torchmetrics.IoU(3, ignore_index=0)
print(iou(torch.tensor([[1,2,1,1]]), torch.tensor([[2,1,1,0]])))
print(iou(torch.tensor([[1,2,1,0]]), torch.tensor([[2,1,1,0]])))
> tensor(0.1250)
tensor(0.1667)
```

### Expected behavior

Predicting a '0' here should not modify the score, both should give 0.1667

### Environment

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Linux & Windows
 - How you installed PyTorch (`conda`, `pip`, source): both
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: 
 - GPU models and configuration:
 - Any other relevant information: 

### Additional context

The ignore_index is implemented like [this](https://github.com/PyTorchLightning/metrics/blob/master/torchmetrics/functional/classification/iou.py#L39):
```
if ignore_index is not None and 0 <= ignore_index < num_classes:
    scores = torch.cat([
        scores[:ignore_index],
        scores[ignore_index + 1:],
    ])
```
This is incorrect as it does not provide the right union value. Instead, the confmat should be stripped of its ignore_index column and line.

This can be done with this line provided it is put before the computation of the intersection and union:
`confmat = confmat[torch.arange(confmat.size(0)) != ignore_index].T[[ignore_index != torch.arange(confmat.size(0))]].T`

**Comment by SkafteNicki** [comment]
Hi @CSautier,
Thanks for raising this issue. Would you be up for sending a PR? :]
