### ISSUE TITLE
FID with custom feature extractor crashes on compute() when torchmetrics[image] is not installed

### ISSUE THREAD

**Issue by jordan-benjamin** [PyTorchLightning/metrics#316]
## 🐛 Bug

Hi there! 

I'm trying to use TorchMetrics' FID metric with a custom feature extractor, without having to pip install the `torchmetrics[image]` package. However, if I don't have the additional package installed, the metric crashes when calling `compute()` due to:

```
AttributeError: module 'scipy' has no attribute 'linalg'
``` 

If I import `scipy.linalg` myself in my script, the call to `compute()` succeeds.

Alternatively, if I install `torchmetrics[image]` and then run my code without importing `scipy.linalg` myself, the call also succeeds.

All of this is documented in [this notebook example](https://colab.research.google.com/drive/1Oi4OwOZ_kJh2MTtq__cjvE-EQGO1Lo5x?usp=sharing).

### To Reproduce

A minimal example of code that fails when `torchmetrics[image]` is not installed is:

```python
from torchmetrics import FID
import torch
from torch import nn

class DummyFeature(nn.Module):
    def forward(self, x):
        return torch.ones(x.shape[0], 64)

metric = FID(feature=DummyFeature())

img1 = torch.ones(10,3,64,64, dtype=torch.uint8)
img2 = torch.ones(10,3,64,64, dtype=torch.uint8)

metric(img1, real=True)
metric(img2, real=False)

metric.compute()
```

which gives the following error.

```
AttributeError                            Traceback (most recent call last)
<ipython-input-2-4daaa64dd003> in <module>()
     15 metric(img2, real=False)
     16 
---> 17 metric.compute()

3 frames
/usr/local/lib/python3.7/dist-packages/torchmetrics/metric.py in wrapped_func(*args, **kwargs)
    324                 dist_sync_fn=self.dist_sync_fn, should_sync=self._to_sync, restore_cache=self._restore_cache
    325             ):
--> 326                 self._computed = compute(*args, **kwargs)
    327 
    328             return self._computed

/usr/local/lib/python3.7/dist-packages/torchmetrics/image/fid.py in compute(self)
    276 
    277         # compute fid
--> 278         return _compute_fid(mean1, cov1, mean2, cov2).to(orig_dtype)

/usr/local/lib/python3.7/dist-packages/torchmetrics/image/fid.py in _compute_fid(mu1, sigma1, mu2, sigma2, eps)
    113     diff = mu1 - mu2
    114 
--> 115     covmean = sqrtm(sigma1.mm(sigma2))
    116     # Product might be almost singular
    117     if not torch.isfinite(covmean).all():

/usr/local/lib/python3.7/dist-packages/torchmetrics/image/fid.py in forward(ctx, input)
     67         # Issue: https://github.com/pytorch/pytorch/issues/9983
     68         m = input.detach().cpu().numpy().astype(np.float_)
---> 69         scipy_res, _ = scipy.linalg.sqrtm(m, disp=False)
     70         sqrtm = torch.from_numpy(scipy_res.real).to(input)
     71         ctx.save_for_backward(sqrtm)

AttributeError: module 'scipy' has no attribute 'linalg'
```

#### Code sample

See the above snippet or [this notebook](https://colab.research.google.com/drive/1Oi4OwOZ_kJh2MTtq__cjvE-EQGO1Lo5x?usp=sharing).

### Expected behavior

The metric should compute successfully without me having to install or import additional packages.

### Environment

Using the default Google Colab environment with `torchmetrics-0.4.0rc1` additionally installed. When `torchmetrics[image]` is not installed, the above snippet crashes.

### Additional context

N/A

**Comment by SkafteNicki** [comment]
Hi @jordan-benjamin,
Thanks for raising this issue. I have opened PR #318 which adds note to FID metric that scipy also needs to be installed (regardless of used feature extractor)

**Comment by SkafteNicki** [comment]
Closing as PR #318 is merged.
