### ISSUE TITLE
Bug in Matthews_correlation_coefficient

### ISSUE THREAD

**Issue by del2z** [PyTorchLightning/metrics#320]
I've tested the ConfusionMatrix and got results similar to the one in [https://en.wikipedia.org/wiki/Matthews_correlation_coefficient](https://en.wikipedia.org/wiki/Matthews_correlation_coefficient). However, the code in [line 23](https://github.com/PyTorchLightning/metrics/blob/c5d83d337f2e0b23ae32f61f0c4f3ebd71f42b23/torchmetrics/functional/classification/matthews_corrcoef.py#L23) is incorrect according to the confusion matrix.
tk, defined as the number of times class k truly occurred, should be the summation along axis=1; pk, on the other hand, is the summation of confusion matrix along axis=0.
Although this mistake does not affect the final result of Matthews correlation coefficient, it may lead to some misunderstanding of the confusion matrix. Hope it can be fixed.

**Comment by SkafteNicki** [comment]
@del2z Thanks for bringing this to our attention. I created PR #321 to fix this.
