### ISSUE TITLE
Using integer >1 as label raise an error in nDCG

### ISSUE THREAD

**Issue by daureg** [PyTorchLightning/metrics#343]
## 🐛 Bug

Using integer >1 as label raise an error in nDCG. I believe it's because the `update` of the base class `RetrievalMetric` is calling `_check_retrieval_inputs` with the default value of `allow_non_binary_target` set to `False`.

#### Code sample

```python
from torchmetrics import RetrievalNormalizedDCG
import torch
indexes = torch.tensor([0, 0, 0, 1, 1, 1, 1])
preds = torch.tensor([0.2, 0.3, 0.5, 0.1, 0.3, 0.5, 0.2])
target = torch.tensor([0, 0, 2, 0, 1, 0, 1])
ndcg = RetrievalNormalizedDCG(k=24)
ndcg(preds, target, indexes=indexes)
```

```python
ValueError                                Traceback (most recent call last)
<command-12376064> in <module>
      5 target = torch.tensor([0, 0, 2, 0, 1, 0, 1])
      6 ndcg = RetrievalNormalizedDCG(k=24)
----> 7 ndcg(preds, target, indexes=indexes)

/databricks/python/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

/databricks/python/lib/python3.8/site-packages/torchmetrics/metric.py in forward(self, *args, **kwargs)
    178         # add current step
    179         with torch.no_grad():
--> 180             self.update(*args, **kwargs)
    181 
    182         if self.compute_on_step:

/databricks/python/lib/python3.8/site-packages/torchmetrics/metric.py in wrapped_func(*args, **kwargs)
    236             self._computed = None
    237             self._update_called = True
--> 238             return update(*args, **kwargs)
    239 
    240         return wrapped_func

/databricks/python/lib/python3.8/site-packages/torchmetrics/retrieval/retrieval_metric.py in update(self, preds, target, indexes)
     96             raise ValueError("`indexes` cannot be None")
     97 
---> 98         indexes, preds, target = _check_retrieval_inputs(indexes, preds, target)
     99 
    100         self.indexes.append(indexes)

/databricks/python/lib/python3.8/site-packages/torchmetrics/utilities/checks.py in _check_retrieval_inputs(indexes, preds, target, allow_non_binary_target)
    579 
    580     if not allow_non_binary_target and target.max() > 1 or target.min() < 0:
--> 581         raise ValueError("`target` must contain `binary` values")
    582 
    583     return indexes.long().flatten(), preds.float().flatten(), target.long().flatten()

ValueError: `target` must contain `binary` values
```

### Expected behavior

Getting a value 

### Environment

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): databricks
 - Python version: 3.8.8
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration: g4dn.4xlarge

**Comment by SkafteNicki** [comment]
cc: @lucadiliello

**Comment by lucadiliello** [comment]
I do not see the reason of passing a value different than `0` and `1` in the labels. A document can be not relevant `0` or `relevant`. What does `2` mean? For this reason only binary values are allowed as labels.

**Comment by daureg** [comment]
Graded relevance is fairly common, for instance with implicit feedback in e-commerce setting: a product can non clicked `0`, clicked `1`, purchased `2`, purchased and not returned after 30 days `3`. It's mentioned in [Wikipedia](https://en.wikipedia.org/wiki/Discounted_cumulative_gain#Cumulative_Gain) and in fact, the functional version of ndcg [allows non binary label](https://github.com/PyTorchLightning/metrics/blob/18056a51aed652534bb5e5e9aff5c305274e0c77/torchmetrics/functional/retrieval/ndcg.py#L51) in accordance with [the documentation](https://torchmetrics.readthedocs.io/en/v0.4.0/references/modules.html#retrievalnormalizeddcg):
> Works with binary or positive integer target data.

**Comment by lucadiliello** [comment]
I didn't really take into account that possibility, mea culpa, do you think you could implement it by opening a PR?
