### ISSUE TITLE
[CI] Test TorchMetrics with PL releases

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/metrics#346]
## 🚀 Feature

The latest TM release introduced a wrong design causing ddp to hang in previous version of PyTorch Lightning.

To avoid this in the future, we should test TM vs `N` previous of Lightning before realising.

Proposal:

* On release CI run a matrix with multiple Lightning version:
      - Clone Lightning
      - Run Lightning tests with current metric version
      - If they all pass, Metric should be backward compatible and can be released !

**Comment by tchaton** [comment]
@Borda Any thoughts on feasibility ?

**Comment by Borda** [comment]
it is already there, you just need to add a proper test, I mentioned in https://github.com/PyTorchLightning/pytorch-lightning/pull/8231#pullrequestreview-697148399
https://github.com/PyTorchLightning/metrics/blob/master/integrations/test_metric_lightning.py
