### ISSUE TITLE
Logits and multilabel: Add support for threshold <= 0?

### ISSUE THREAD

**Issue by leonweber** [PyTorchLightning/metrics#350]
## 🚀 Feature
Add support for logit input in multilabel classification

### Motivation

The docs state that F1 accepts logits and supports multilabel. However, if one uses logits as input in multilabel classification with a NLL loss, the threshold cannot be set to its' natural value 0:
```python
f1 = F1(num_classes=3, threshold=0.0)
ValueError: The `threshold` should be a float in the (0,1) interval, got 0.0
```
This makes logits input for F1 basically unusable in a multilabel task.

### Pitch

It might be a good idea to (a) prominently point out in the docs that the threshold has to be adapted for logits input and (b) allow thresholds smaller than 0.

**Comment by Borda** [comment]
@SkafteNicki I think we forgot this after #200

**Comment by SkafteNicki** [comment]
Yes, most definitely, going to send a fix soon :]
