### ISSUE TITLE
Add Bleu score

### ISSUE THREAD

**Issue by SkafteNicki** [PyTorchLightning/metrics#352]
### Motivation

Add Blue score to future NLP package:
* class implementation can be taken from flash: https://github.com/PyTorchLightning/lightning-flash/blob/master/flash/text/seq2seq/translation/metric.py
* already have a functional version in https://github.com/PyTorchLightning/metrics/blob/master/torchmetrics/functional/nlp.py that just need to be move to a new file in `functional/text/bleu.py` (for consistency)

### Additional context

After merge to torchmetrics + official release the metric should be deprecated from flash + lightning-transformer.

**Comment by karthikrangasai** [comment]
@SkafteNicki 
I would like to work on this issue.

I have moved the file `functional/nlp.py` to `functional/text/blue.py`. Where should I put the class implementation ??

**Comment by SkafteNicki** [comment]
Hi @karthikrangasai,
Please put the class implementation in a new folder `text` inside a file called `bleu`

**Comment by karthikrangasai** [comment]
@SkafteNicki 
I have created a PR with the changes suggested. 

I think tests and docs have to be updated, could you guide me on this ?
