### ISSUE TITLE
Addition of more audio metrics

### ISSUE THREAD

**Issue by SkafteNicki** [PyTorchLightning/metrics#353]
### Motivation

Feedback based on the newly release audio package (https://twitter.com/ai_rishikesh/status/1412707569710166019), here are a couple of other audio metrics it would be great if we added:
* PESQ (https://en.wikipedia.org/wiki/Perceptual_Evaluation_of_Speech_Quality)
* STOI (https://ieeexplore.ieee.org/document/5495701)
* MCD (https://github.com/MattShannon/mcd)

cc: @quancs

**Comment by quancs** [comment]
PESQ and STOI are in plan. The PESQ is limited by its copy right owner. And seems we cannot translate its c++ code to pytorch see [here](https://github.com/vBaiCai/python-pesq/blob/master/pypesq/pesq.h). 

PESQ refs: https://github.com/vBaiCai/python-pesq, https://github.com/ludlows/python-pesq, https://github.com/aliutkus/speechmetrics
STOI refs: https://github.com/mpariente/pystoi, https://github.com/mpariente/pytorch_stoi, https://github.com/aliutkus/speechmetrics

**Comment by quancs** [comment]
Is it good to use pytorch to wrap the c++ implementation of PESQ, like other implementations?
@SkafteNicki

**Comment by SkafteNicki** [comment]
@Borda can you help with answering what to do here? They use MIT license but they are against [replications](https://github.com/vBaiCai/python-pesq/blob/d870dfa9972afa0b82ad0b0d01341010343907ba/pypesq/pesq.h#L44-L45)

**Comment by Borda** [comment]
according to their statement, we cannot use even modified their code... :/
I guess the only way would be to integrate it as dependency or ask @vBaiCai @SKb10 if they are willing to contribute to TM

**Comment by quancs** [comment]
> 
> 
> according to their statement, we cannot use even modified their code... :/
> I guess the only way would be to integrate it as dependency or ask @vBaiCai @SKb10 if they are willing to contribute to TM

Can we use the c++ code of PESQ as @vBaiCai and @SKb10 do? If we add the c++ code into TM, is it a duplication?

The statement are copied below:
```
The user cannot:

1.	alter, duplicate, modify, adapt, or translate in whole or in
      part any aspect of the PESQ Algorithm and or PESQ Software
2.	sell, hire, loan, distribute, dispose or put to any commercial
      use other than those permitted below in whole or in part any
      aspect of the PESQ Algorithm and or PESQ Software
```

**Comment by quancs** [comment]
I checked the [speechmetric](https://github.com/aliutkus/speechmetrics) implementation...
It uses the two implementation as dependency......

**Comment by quancs** [comment]
> 
> 
> according to their statement, we cannot use even modified their code... :/
> I guess the only way would be to integrate it as dependency or ask @vBaiCai @SKb10 if they are willing to contribute to TM

This might be the only way...

**Comment by quancs** [comment]
Sorry, I forgot our disscussion here... @Borda 
I closed my pull request of pesq... and I have invited [ludlows](https://github.com/ludlows/python-pesq/issues/32) to do this job.

**Comment by quancs** [comment]
Can you give an invitation to [mpariente](https://github.com/mpariente/pystoi) for stoi? His stoi is widely used in audio community.

**Comment by quancs** [comment]
As for MCD, I am not familiar with it. You can invite the owner of  MCD package (https://github.com/MattShannon/mcd).
