### ISSUE TITLE
ValueError Multiclass F1 with Logits

### ISSUE THREAD

**Issue by TheBigJones** [PyTorchLightning/metrics#354]
## 🐛 Bug

When logits are greater than num_classes an error is raised.
ValueError: The highest label in `preds` should be smaller than `num_classes`.

### To Reproduce

Run the code below. Shapes of preds is [8,16] and targets [8], 8 samples and 16 classes.

#### Code sample

```py
import torch
import torchmetrics

preds = torch.tensor([
[-6.5553, 9.6432, -0.4769, 0.1175, 3.5849, -0.0728, -3.4077, 2.4942, -4.1983, -5.5861, -1.1669, -2.3120, 0.0785, 0.4402, -3.4203, 3.1583],
[-3.8317, 4.4087, 3.7377, 2.1027, 2.4214, 6.2215, -0.4169, 1.9238, 0.7759, -2.5961, -0.0995, -3.7249, -3.0330, -0.2375, -4.5072, 1.7386],
[-5.3307, 1.7155, -1.9727, -3.7732, 0.1009, 5.8277, -2.7174, -0.2504, -3.9892, -5.2998, -0.3233, -2.7954, -3.9205, -1.1068, 2.7772, 3.2727], 
[-1.6112, -1.5625, 1.3922, 0.7977, -2.6054, 2.9645, 3.4701, 7.3668, -2.1667, -6.2279, -1.1098, -1.9391, -2.8797, -3.4399, 0.2832, -1.8142],
[-1.6622, -1.1403, -3.0026, -2.4874, -0.2193, -2.1577, -2.2311, 0.5503, -3.0843, -0.7532, 1.0839, 2.1035, 3.4447, -0.3838, 3.3565, -0.0869]
[0.8351, -5.5552, -4.7961, -4.7794, -0.7726, -3.9873, -1.1969, -0.4034, -3.8699, -1.1991, 0.6840, 0.7169, 3.7095, -1.3286, 5.9828, -0.2510],
[-3.8948, 1.4767, 0.6704, -1.0283, 0.9553, 5.7985, 0.4266, 3.5262, -2.3887, -4.7733, -1.0456, -2.8571, -4.6838, -0.9178, -0.3474, 1.8034],
[-8.9989, 16.9431, -0.6238, 0.1971, 6.8480, -5.7200, -6.6676, 4.6525, -4.9335, -10.6909, -4.2943, -1.6526, 3.8292, 2.1301, -2.1880, 3.1771]
])
targets = torch.tensor([1,2,3,4,5,6,7,8], dtype=torch.int32)

f1 = torchmetrics.F1(num_classes=16)
f1(preds, targets)

```

### Expected behavior
As logits in theory can be between -inf and +inf there shouldn't be an error when logits are greater than the number of classes (in this case the 16.9431 in the preds for the last sample).

### Environment

 - PyTorch Version (e.g., 1.0): 1.9.0+cu111
 - OS (e.g., Linux): Win
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8.10
 - CUDA/cuDNN version: CUDA 11
 - GPU models and configuration: RTX 3070
 - Any other relevant information:

### Additional context

_check_num_classes_mc in checks.py checks if num_classes is <= the max value in preds. As in my example my network outputs logits that are greater than the number of classes I have defined, thus the check throws and error.

**Comment by SkafteNicki** [comment]
Hi @TheBigJones,
Thanks for raising this issue. I have opened PR #357 that removes this check.
