### ISSUE TITLE
BERTScore Implementation

### ISSUE THREAD

**Issue by satyajitghana** [PyTorchLightning/metrics#365]
## 🚀 Feature
BertScore Implementation for TextGeneration in NLP

### Motivation

BERTScore computes a similarity score for each token in the candidate sentence with each token in the reference sentence. However, instead of exact matches, we compute token similarity using contextual embeddings. 

### Pitch

need an api like `bert_score(translate_corpus, reference_corpus, ...)`

Related Paper: https://arxiv.org/abs/1904.09675

A Really Good Explanation: https://wiki.math.uwaterloo.ca/statwiki/index.php?title=BERTScore:_Evaluating_Text_Generation_with_BERT

### Alternatives

This is an implementation: https://github.com/Tiiiger/bert_score

**Comment by gagan3012** [comment]
Can I work on this?

**Comment by SkafteNicki** [comment]
@gagan3012 still interested in implementing this?

**Comment by gagan3012** [comment]
Yes I am!
