### ISSUE TITLE
Squad V2 Question Answering Task metric

### ISSUE THREAD

**Issue by gagan3012** [PyTorchLightning/metrics#366]
## 🚀 Feature

For the Question Answering Task, we would need the SQUADv2 metrics  
I would like to have it here

**Comment by Borda** [comment]
@gagan3012 how is it going? :rabbit:

**Comment by karthikrangasai** [comment]
Hello all,
I can take this up if work hasn't started yet.

**Comment by gagan3012** [comment]
Sure go ahead @karthikrangasai
