### ISSUE TITLE
SMAPE regression error

### ISSUE THREAD

**Issue by hugoperrin** [PyTorchLightning/metrics#372]
## 🚀 Feature
Add SMAPE regression error to the regression metrics

### Motivation

There was the presence of MAPE but not SMAPE. As a computer vision research engineer, I'm more used to look at SMAPE instead of MAPE because SMAPE is bounded between 0 and 1 naturally, which makes it easier to interpret and compare.

### Pitch

I implemented the metric in a fork as it is a relatively easy metric to add in, so I figured it would be a quick win to add it in :).
It's actually quite straightforward to implement as it is quite similar to MAPE/MSE and so on!

### Additional context

I have the code ready for a PR with tests already as the code needed is quite light.

**Comment by hugoperrin** [comment]
All tests and docs are running on the code I have, so it should not be a long task from now on. Let me know if I am supposed to create the PR now, or if I need for someone to approve the relevancy of the feature before before creating it :)

**Comment by SkafteNicki** [comment]
Hi @hugoperrin, please feel free to send us your PR, sounds like a great enhancement :]

**Comment by hugoperrin** [comment]
@SkafteNicki Perfect :) The PR has been created, I will have to change a few details regarding the automatic CI, small detail with flake8, will let you know there when it's done (tonight normally :) )
