### ISSUE TITLE
Classification metrics do not return grad

### ISSUE THREAD

**Issue by XiaomoWu** [PyTorchLightning/metrics#388]
## 🐛 Bug

Classification metrics, for example, AveragePrecision, don't return gradient.

### To Reproduce

```python
import torch 
import torchmetrics

x = torch.tensor([0.1, 0.6, 0.3], requires_grad=True)
y = torch.tensor([0, 1, 1])

loss = torchmetrics.AveragePrecision()(x, y)
loss.backward() # RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

loss = torchmetrics.MeanSquaredError()(x, y)
loss.backward() # work as expected
```

### Environment

 - PyTorch Version: 1.9.0
 - OS: Ubuntu 21.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.8.5
 - CUDA/cuDNN version: 11.1

**Comment by Borda** [comment]
@XiaomoWu it is expected, as you can also see it is not differentiable:
https://github.com/PyTorchLightning/metrics/blob/5e29a6082d381c96d48dd942f903c24fef949343/torchmetrics/classification/average_precision.py#L135-L136

**Comment by XiaomoWu** [comment]
> @XiaomoWu it is expected, as you can also see it is not differentiable:
> https://github.com/PyTorchLightning/metrics/blob/5e29a6082d381c96d48dd942f903c24fef949343/torchmetrics/classification/average_precision.py#L135-L136

I see... Thank you @Borda. One more question and please pardon my ignorance: If I'm doing a classification task, and want to use `torchmetrics` as the loss criterion, which metric should I pick? I can't find any counterparts like the `torch.nn.BCEloss` in pytorch. Of course, I can use `torch.nn.BCEloss`, but I'm worried it won't take care of gradient sync in DDP, which is why I want to use `torchmetrics`.

**Comment by justusschock** [comment]
@XiaomoWu If you use PyTorch Lightning you can use `torch.nn.BCELoss` since lightning takes care of the syncing there.
