### ISSUE TITLE
Add docstrings to protected functions

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/metrics#389]
## 📚 Documentation

Add docstrings to all protected functions at least tell what are the arguments for...
This can see easily implemented in multiple PRs :rabbit:

**Comment by DevPranjal** [comment]
Hi @Borda, I am new to PL, and would like to start working on this to gain some insights.

**Comment by Borda** [comment]
@DevPranjal awsome! let do it in some smaller steps... :rabbit: Feel free to ping me on slack :]

**Comment by DevPranjal** [comment]
Great, thanks!

**Comment by sameetsinghsidhu** [comment]
Hi @Borda I would like to contribute to this :)

**Comment by SkafteNicki** [comment]
@DevPranjal should we still keep this open?

**Comment by DevPranjal** [comment]
I think we are pretty much done. We can close this for now, I will surely make a PR incase I find a group of un-documented functions. Looking forward to contribute more, feel free to tag me in an issue! Thanks :)

**Comment by SkafteNicki** [comment]
@DevPranjal sounds good to me :]
Great that you want to contribute some, will let you know if we have something .
