### ISSUE TITLE
Error At Percentile

### ISSUE THREAD

**Issue by YovelRom** [PyTorchLightning/metrics#393]
## 🚀 Feature
A regression metric that measures the error of the model at a certain percentile (e.g, in a price prediction model, 95% of the houses will be within 10,000$ of the projected price).

### Motivation

I personally used this metric in two very different projects, so I figured it could be useful to other people. It's a useful metric when trying to estimate risks from using the model in real- life settings, since it helps to quantify the amound of cases where the prediction will go horribly wrong.

### Pitch

I already wrote the code and I'm using it, so this should be pretty straightforward :)

**Comment by SkafteNicki** [comment]
Hi @YovelRom, seems like a great addition to the regression package.
Would you be up for sending a PR?

**Comment by Borda** [comment]
@YovelRom are interested in contributing this metric? :rabbit:

**Comment by SkafteNicki** [comment]
After taking a second look at this, I have not been able to find any references or open-source implementation of this metric. Closing the issue.
