### ISSUE TITLE
Case `reduction=None` not handled in CosineSimilarity

### ISSUE THREAD

**Issue by FlorianMF** [PyTorchLightning/metrics#398]
https://github.com/PyTorchLightning/metrics/blob/2c528bdc1d0e5c292c769227e127aad559b3dd21/torchmetrics/functional/regression/cosine_similarity.py#L33-L39

Neither the functional nor the class version accepts reduction=None. To be aligned with the classification metrics it would be good to allow this as well.

**Comment by FlorianMF** [comment]
We could change this to either:
```
reduction_mapping = {"sum": torch.sum, "mean": torch.mean, "none": lambda x: x}
reduction_mapping[None]=reduction_mapping['none']
```
or
```
reduction_mapping = {"sum": torch.sum, "mean": torch.mean, "none": lambda x: x, None: lambda x: x}
```

**Comment by SkafteNicki** [comment]
Hi @FlorianMF, thanks for opening this issue. I created PR #400 that should fix it.
