### ISSUE TITLE
Ambiguity in semantic ordering of kernel_size and padding computation in SSIM

### ISSUE THREAD

**Issue by ad12** [PyTorchLightning/metrics#414]
### Ambiguity in semantic ordering of `kernel_size` and padding computation
The semantic ordering of `kernel_size` may not match the ordering of the computed padding values. Based on how the kernel is created in `_gaussian_kernel`, `kernel_size` corresponds to the `(height, width)` of the kernel. [The current code](https://github.com/PyTorchLightning/metrics/blob/c9d36b2fa2e65155b3ca2d350b40a932b5a316fb/torchmetrics/functional/image/ssim.py#L87) the computes padding uses `kernel_size[0]` to compute the padding for the width dimension of the image and `kernel_size[1]` to compute the padding for the height dimension of the image. I believe these should be flipped.

This issue may not manifest in visible errors when the height and width of the kernel are the same, but may present issues when the two are different.

#### Potential Solution
Change `pad_w = (kernel_size[1] - 1) // 2` and `pad_w = (kernel_size[1] - 1) // 2`

I am happy to provide some PRs for these if the solutions seem reasonable.

**Comment by ad12** [comment]
Apologies, the first point about the difference from scikit-image does not apply. Editing the post to indicate that.

**Comment by SkafteNicki** [comment]
@ad12 sounds good to me. Please feel free to send a PR :]

**Comment by ad12** [comment]
will tackle this later this week, thanks!
