### ISSUE TITLE
Let IDE(s) know public symbols

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/metrics#420]
## 🚀 Feature (or Bug?)
I'm using Pylance on VSCode, and it doesn't autocomplete, for example, `Accuracy` even if I typed the following:

```python
from torchmetrics import Ac
```

This is because imported symbols are considered private by default (by at least pylance (pyright) as documented [here](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface)).

### Motivation
For better coding experience (autocomplete + docstring reference) :]

### Pitch
As stated in https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface, we have the following options to explicitly make symbols public.

#### 1. Add `__all__` to `__init__.py` files.
```python
# torchmetrics/__init__.py
from torchmetrics.classification import (
    Accuracy,
    ...
)
__all__ = [
    "Accuracy",
    ...
]
```

#### 2. Use wildcard imports.
```python
# torchmetrics/__init__.py
from torchmetrics.classification import *

# torchmetrics/classification/__init__.py
__all__ = [
    "Accuracy",
    ...
]
```

#### 3. Use redundant symbol aliases.
```python
# torchmetrics/__init__.py
from torchmetrics.classification import (
    Accuracy as Accuracy,
    ...
)
```

### Additional context
https://github.com/microsoft/pylance-release/issues/1032
https://github.com/microsoft/pyright/pull/1877

**Comment by SkafteNicki** [comment]
@akihironitta sounds good to me :]
I would prefer option 1 but have no strong opinions here.
