### ISSUE TITLE
R2Score errors on size 1 batch updates

### ISSUE THREAD

**Issue by ed1d1a8d** [PyTorchLightning/metrics#423]
The following code should work but crashes:
```
import torch
from torchmetrics import R2Score

x = R2Score()
x.update(preds=torch.tensor([1, 2]), target=torch.tensor([1, 2]))
x.update(preds=torch.tensor([1]), target=torch.tensor([1]))
print(x.compute())
```
The crash is due to
https://github.com/PyTorchLightning/metrics/blob/5a2388ccaa97cc3608b1fa28879f77436434a6d6/torchmetrics/functional/regression/r2.py#L37-L38

**Comment by SkafteNicki** [comment]
Hi @ed1d1a8d, thanks for raising this issue. I created PR #426 that solves this.
