### ISSUE TITLE
implement own metrics or use lighter packages

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/metrics#433]
## 🚀 Feature

revisit 3rd-party dependencies and if possible make own implementation or use a lighter package 

### Motivation

keep the TM dependency light, and use other packages only as a reference

### Alternatives

use another package that has less dependencies and still use this one as reference

### Additional context

https://github.com/PyTorchLightning/metrics/blob/525642df8c3f3f5f93cdd22b6b9cd802a3854634/requirements/image.txt#L3

https://github.com/PyTorchLightning/metrics/blob/525642df8c3f3f5f93cdd22b6b9cd802a3854634/requirements/text.txt#L1-L3

Particular tasks:
- #432

**Comment by stancld** [comment]
@Borda May I have a look at the `rouge_score` metric?

**Comment by Borda** [comment]
> @Borda May I have a look at the `rouge_score` metric?

that would be great! looking forward to see draft PR :rabbit:

**Comment by kingyiusuen** [comment]
@Borda I'd love to contribute to this project. Do you mind if I work on the WER metric to remove the dependency of jiwer?

**Comment by Borda** [comment]
> Do you mind if I work on the WER metric to remove the dependency of jiwer?

wow, that you, that would be really great! :rabbit: 
cc: @SeanNaren
