### ISSUE TITLE
`SpearmanCorrcoef` bug due to incorrect ranking

### ISSUE THREAD

**Issue by amanjitsk** [PyTorchLightning/metrics#444]
## 🐛 Bug

There is a bug in the `_rank_data` function [here](https://github.com/PyTorchLightning/metrics/blob/master/torchmetrics/functional/regression/spearman.py#L50), that causes a downstream error in the Spearman correlation coefficient calculation.

#### Code sample

```python
>>> import numpy as np
>>> import torch
>>> from scipy import stats
>>> from torchmetrics import SpearmanCorrcoef
>>> a = np.array([1., 0., 4., 1., 0., 3. ,0.])
>>> b = np.array([4., 0., 3., 3., 3., 1., 1.])
>>> a_t, b_t = torch.from_numpy(a), torch.from_numpy(b)
>>> spearman = SpearmanCorrcoef()
>>> print(f"scipy.stats.spearman = {stats.spearmanr(a, b).correlation}")
scipy.stats.spearman = 0.3529411764705882
>>> print(f"torchmetrics.SpearmanCorrcoef = {spearman(a_t, b_t)}")
torchmetrics.SpearmanCorrcoef = 0.10714283035714954
```
Upon further inspection, I found that the discrepancy was due to the `_rank_data` function [here](https://github.com/PyTorchLightning/metrics/blob/master/torchmetrics/functional/regression/spearman.py#L35)

```python
>>> from torchmetrics.functional.regression import spearman
>>> spearman._rank_data(a_t)
tensor([4., 1., 7., 5., 2., 6., 3.], dtype=torch.float64)
>>> stats.rankdata(a)
array([4.5, 2. , 7. , 4.5, 2. , 6. , 2. ])
```
At first I thought that the `_rank_data` function maybe is comparable to the `stats.rankdata` with the `method='ordinal'` kwarg (as the behavior of `_rank_data` can be reproduced in this __specific__ case by setting `method='ordinal'` in `scipy.stats.rankdata`).
But the problem is much worse, as the documentation for `_rank_data` itself claims that it is equivalent to the `method='average'` option for `stats.rankdata`. Turns out the `_rank_data` function [here](https://github.com/PyTorchLightning/metrics/blob/master/torchmetrics/functional/regression/spearman.py#L50) has a bug, which can be fixed by 
changing 
```python
condition = rank == r
```
to 
```python
condition = data == r
```
on Line 50

### Environment

- PyTorch Version (e.g., 1.0): 1.9.0+cu102
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source):
- Python version: 3.7.9
- CUDA/cuDNN version: CUDA 10.2 / CUDNN 10.2-v7.6.5.32

### Additional context

I was trying to get the behavior of `SpearmanCorrcoef` to match that of `scipy`. Turns out there is a minor typo in the `_rank_data` function in `torchmetrics/functional/regression/spearman.py` (that produces non-sensical results in the worst-case, i.e. when the number of elements to be ranked is smaller than the minimum of the value of all elements)

**Comment by SkafteNicki** [comment]
Hi @amanjitsk, thanks for reporting this issue :]
I have opened PR #448 that should fix this issue and added test to make sure it indeed is fixed
