### ISSUE TITLE
Using AUROC with DDP not working as expected

### ISSUE THREAD

**Issue by sahil711** [PyTorchLightning/metrics#445]
## 🐛 Bug

I was trying to use a multi-gpu setup for training my model. I have a classification model for which I want to calculate AUC.
I am getting the following error from one of the gpus:

`ValueError: No positive samples in targets, true positive value should be meaningless`

This error makes sense to me as the batch on this gpu might not have any positive sample and hence AUC is meaningless. But I wanted the AUC calculation to happen at an epoch level and not batch level (post accumulation from all the devices).

#### Code sample
Here is a sample code of what I have wrriten:

from torchmetrics.classification.auroc import AUROC

class LitMod(pl.LightningModule):
    
    def __init__(self):
        super().__init__()
        self.model = Model()
        self.criteria = nn.CrossEntropyLoss()
        self.metrics = AUROC()
    
    def training_step(self, batch, batch_idx):
        y = batch["target"]
        preds = self.model(batch)
        loss = self.criteria(preds, y)
        auc = self.metrics(preds[:, 1], y)
        log_dict = {"train_loss": loss, "train_auc": auc}
        self.log_dict(dictionary=log_dict, on_step=False, on_epoch=True, prog_bar=True)
        return {"loss": loss}

### Expected behavior

My expectation was given that, I have kept the `on_step` flag as `False`, this calculation would only happen at an epoch level. 
This is also stated in the [docs](https://torchmetrics.readthedocs.io/en/stable/pages/lightning.html):
`Lightning will log the metric based on on_step and on_epoch flags present in self.log(...). If on_epoch is True, the logger automatically logs the end of epoch metric value by calling .compute()`

**How to make this work, such that calculation happens at an epoch level post accumulation from all the devices?**

### Environment

- PyTorch Version : 1.7.1
- OS : Ubuntu 18.04
- How you installed PyTorch : pip
- Python version: 3.8
- GPU models and configuration: v100 x 4

**Comment by maximsch2** [comment]
```
    auc = self.metrics(preds[:, 1], y)
    log_dict = {"train_loss": loss, "train_auc": auc}
```

Here you are trying to compute AUC on single batch and then log it. Instead, you should do:
```
    self.metrics.update(preds[:, 1], y)
    log_dict = {"train_loss": loss, "train_auc": self.metrics}
```

(or alternatively, keep `update` in `training_step` and do `self.log('train_auc', self.metrics.compute())` in `on_training_epoch_end`)

**Comment by SkafteNicki** [comment]
Yes, as @maximsch2 is stating, you have a few options:
1. Call `update` instead of `compute`: 
```python
self.metrics.update(preds[:, 1], y)
```
2. Initialize metric with `compute_on_step=False`. This essentially turns the call to `forward` into `update`:
```python
self.metrics = AUROC(compute_on_step=False)
```
3. Instead of relying on `on_step` and `on_epoch` in `self.log`, call it where you want the value logged:
```python
def training_step(self, batch, batch_idx):
    ...
    self.metrics.update(preds[:, 1], y)
    ...

def training_epoch_end(self, outputs):
    self.log('train_auc', self.metrics.compute())
```
Closing issue.
