### ISSUE TITLE
ValueError: When your inputs are multi-dimensional multi-class, you have to set the `mdmc_reduce` parameter

### ISSUE THREAD

**Issue by MeganClark-Robinson** [PyTorchLightning/metrics#447]
## 🐛 Bug

I am trying to find precision but it returns:

 "When your inputs are multi-dimensional multi-class, you have to set the `mdmc_reduce` parameter"
ValueError: When your inputs are multi-dimensional multi-class, you have to set the `mdmc_reduce` parameter

----
`def calc_precision_and_recall(self, y_pred, y_true, step="val"):

        y_max_pred, y_true, _ = _input_format_classification(y_pred[-1], y_true, threshold=0.5)
        precision = self.precision_metric(y_max_pred, y_true)
        recall = self.recall_metric(y_max_pred, y_true)
        #if step == "val":
        #    self.log_precision_and_recall(precision, recall, step=step)
        return precision, recall`
-----
`class PrecisionOverClasses(Precision):

    def __init__(self, num_classes: int = 1, threshold: float = 0.5, average: str = 'micro', mdmc_reduce: Optional[str] = None, #multilabel: bool = False,
            compute_on_step: bool = True, dist_sync_on_step: bool = False, process_group: Optional[Any] = None, ):
        super().__init__(num_classes=num_classes, threshold=threshold, average=average, mdmc_reduce = mdmc_reduce, #multilabel=multilabel,
                         compute_on_step=compute_on_step, dist_sync_on_step=dist_sync_on_step, process_group=process_group)
    def compute(self):
        return self.true_positives.float() / self.predicted_positives`
------
`class RecallOverClasse(Recall):

    def __init__(self, num_classes: int = 1, threshold: float = 0.5, average: str = 'micro', #multilabel: bool = False,
            compute_on_step: bool = True, dist_sync_on_step: bool = False, process_group: Optional[Any] = None, ):
        super().__init__(num_classes=num_classes, threshold=threshold, average=average, #multilabel=multilabel,
                         compute_on_step=compute_on_step, dist_sync_on_step=dist_sync_on_step, process_group=process_group)
    def compute(self):
        return self.true_positives.float() / self.actual_positives`

**Comment by SkafteNicki** [comment]
Hi @MeganClark-Robinson, could you kindly report what the shape of `y_pred[-1], y_true` is?

**Comment by MeganClark-Robinson** [comment]
> Hi @MeganClark-Robinson, could you kindly report what the shape of `y_pred[-1], y_true` is?

Hi. They are Tensor:

def training_step(self, batch, batch_idx):
        stem, y_hat, y_true = batch
        y_pred = self.forward(stem)
        loss = self.loss_function(y_pred, y_true)
        self.log("loss", loss, on_epoch=True, on_step=True, prog_bar=True)
        precision, recall = self.calc_precision_and_recall(y_pred, y_true, step="train")
        acc_stages=self.train_acc_stages(y_pred, y_true)
        acc_stages_dict = {f"train_S{s+1}_acc":acc_stages[s] for s in range(len(acc_stages))}
        acc_stages_dict["train_acc"] = acc_stages_dict.pop(f"train_S{len(acc_stages)}_acc") # Renaming metric of last Stage
        self.log_dict(acc_stages_dict, on_epoch=True, on_step=False)
        return {"loss":loss, "precision": precision, "recall": recall}

**Comment by MeganClark-Robinson** [comment]
> Hi @MeganClark-Robinson, could you kindly report what the shape of `y_pred[-1], y_true` is?

Mdmc_reduce parameter is not defined in Precision and Recall classes.

**Comment by SkafteNicki** [comment]
> 
> 
> > Hi @MeganClark-Robinson, could you kindly report what the shape of `y_pred[-1], y_true` is?
> 
> Mdmc_reduce parameter is not defined in Precision and Recall classes.

Depending on what you want to do you should either set the parameter to `'samplewise' or `global`. You can read more about the difference in the documentation: https://torchmetrics.readthedocs.io/en/latest/references/modules.html#id4

**Comment by MeganClark-Robinson** [comment]
> > > Hi @MeganClark-Robinson, could you kindly report what the shape of `y_pred[-1], y_true` is?
> > 
> > 
> > Mdmc_reduce parameter is not defined in Precision and Recall classes.
> 
> Depending on what you want to do you should either set the parameter to `'samplewise' or `global`. You can read more about the difference in the documentation: https://torchmetrics.readthedocs.io/en/latest/references/modules.html#id4

Thank you. I read that. But mdmc_reduce parameter is only defined in `stat_scores` class, not in `Precision` and `Recall` classes.

https://torchmetrics.readthedocs.io/en/latest/references/modules.html#statscores

**Comment by SkafteNicki** [comment]
Alright, I see the confusion here. For precision and recall the parameter is named `mdmc_average` which gets translated to the `mcmc_reduce` parameter here:
https://github.com/PyTorchLightning/metrics/blob/484477a24a22b18315486da6be65eed5135e39f1/torchmetrics/classification/precision_recall.py#L144
So just set `mdmc_average` instead.

**Comment by MeganClark-Robinson** [comment]
> Alright, I see the confusion here. For precision and recall the parameter is named `mdmc_average` which gets translated to the `mcmc_reduce` parameter here:
> https://github.com/PyTorchLightning/metrics/blob/484477a24a22b18315486da6be65eed5135e39f1/torchmetrics/classification/precision_recall.py#L144
> 
> 
> So just set `mdmc_average` instead.

Thanks a lot. Solved
