### ISSUE TITLE
Accuracy for multistage classification problem

### ISSUE THREAD

**Issue by MeganClark-Robinson** [PyTorchLightning/metrics#458]
## 🐛 Bug

I am trying to solve a multistage classification problem, using multistage temporal convolutional networks (MSTCN). I defined accuracy as follows:

```py
class AccuracyStages(Metric):
    def __init__(self, num_stages=1, dist_sync_on_step=False):
        super().__init__(dist_sync_on_step=dist_sync_on_step)
        self.add_state("total", default=torch.tensor(0), dist_reduce_fx="sum")
        self.num_stages = num_stages
        for s in range(self.num_stages):
            self.add_state(f"S{s + 1}_correct", default=torch.tensor(0), dist_reduce_fx="sum")

    def update(self, preds: torch.Tensor, target: torch.Tensor):
        self.total += target.numel()
        for s in range(self.num_stages):
            preds_stage, target, _ = _input_format_classification(preds[s], target, threshold=0.5)
            assert preds_stage.shape == target.shape

            s_correct = getattr(self, f"S{s + 1}_correct")
            s_correct += torch.sum(preds_stage == target)
            setattr(self, f"S{s + 1}_correct", s_correct)

    def compute(self):
        acc_list = []
        for s in range(self.num_stages):
            s_correct = getattr(self, f"S{s + 1}_correct")
            acc_list.append(s_correct.float() / self.total)
        return acc_list

```

### Expected Behavior

1) When the number of stages (`num_stages = 1`) is one, it gives a wrong result for accuracy (around 6), the accuracy must be between 0 and 1. 
2) When I increase the number of stages it returns:
ValueError: If `preds` have one dimension more than `target`, the shape of `preds` should be (N, C, ...), and the shape of `target` should be (N, ...).

**Comment by SkafteNicki** [comment]
Hi @MeganClark-Robinson,
What is the shape of the `preds` and `target` tensor that you tries to use?

**Comment by MeganClark-Robinson** [comment]
> Hi @MeganClark-Robinson,
> What is the shape of the `preds` and `target` tensor that you tries to use?

@SkafteNicki 
For example, when number of stages is one, the shape of the `preds` is `torch.Size([1, 1, 7, 4])` and the shape of `target` is `torch.Size([1, 4])`. When I increase the number of stages into two, the shape of the `preds` becomes `torch.Size([2, 1, 7, 3])` and the shape of `target` `torch.Size([1, 3])`. When I set `num_stages = 3`, the shape of `preds` becomes `torch.Size([3, 1, 7, 4])` and the shape of `target` `torch.Size([1, 4])` and it returns:
ValueError: If `preds` have one dimension more than `target`, the shape of `preds` should be (N, C, ...), and the shape of `target` should be (N, ...).

**Comment by SkafteNicki** [comment]
Hi @MeganClark-Robinson,
Finally found the time to take a stab at this. So here is a working implementation:
```python

import torch
from torchmetrics import Metric
from torchmetrics.utilities.checks import _input_format_classification


class AccuracyStages(Metric):
    def __init__(self, num_stages=1, dist_sync_on_step=False):
        super().__init__(dist_sync_on_step=dist_sync_on_step)
        self.add_state("total", default=torch.tensor(0), dist_reduce_fx="sum")
        self.num_stages = num_stages
        for s in range(self.num_stages):
            self.add_state(f"S{s + 1}_correct", default=torch.tensor(0), dist_reduce_fx="sum")

    def update(self, preds: torch.Tensor, target: torch.Tensor):
        self.total += target.numel()
        for s in range(self.num_stages):
            preds_stage, target_stage, _ = _input_format_classification(preds[s], target)
            assert preds_stage.shape == target_stage.shape

            s_correct = getattr(self, f"S{s + 1}_correct")
            s_correct += torch.sum(preds_stage * target_stage)
            setattr(self, f"S{s + 1}_correct", s_correct)

    def compute(self):
        acc_list = []
        for s in range(self.num_stages):
            s_correct = getattr(self, f"S{s + 1}_correct")
            acc_list.append(s_correct.float() / self.total)
        return acc_list


if __name__ == "__main__":
    batch_size = 1
    num_classes = 7
    extra_dim = 4
    for num_stages in range(1, 4):
        metric = AccuracyStages(num_stages=num_stages)

        preds = torch.randn(num_stages, batch_size, num_classes, extra_dim).softmax(dim=-2)
        target = torch.randint(num_classes, (batch_size, extra_dim))

        val = metric(preds, target)
        print((preds.argmax(dim=-2) == target).float().mean(dim=-1).squeeze()) # for comparing
        print(val)
        print("\n")
```
basically fixed two issues:
* `target` was passed multiple times `_input_format_classification` meaning that after the first stage it was tried being formatted once more which lead to one of the errors.
* In this line `s_correct += torch.sum(preds_stage == target)´ it should instead be `s_correct += torch.sum(preds_stage * target_stage)´ because both have been formatted as one-hot after passing through the `_input_format_classification` function.

Going to close this one. Please open if the issue persist :]
