### ISSUE TITLE
register conda forge

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/metrics#46]
## 🚀 Feature

Publish package also to Conda distribution

### Motivation

Allow user to install from any source

### Additional context

> you can check the documentation at https://conda-forge.org/docs/maintainer/adding_pkgs.html. It’s actually very easy. In short you must submit a PR to https://github.com/conda-forge/staged-recipes. Once the CI is green you can ping conda-forge folks and they will review it. Once done the feedstock will be created and your package built and uploaded to conda forge.

**Comment by Borda** [comment]
waiting for the final release, opened PR https://github.com/conda-forge/staged-recipes/pull/14229

**Comment by SkafteNicki** [comment]
@Borda can this be closed?

**Comment by Borda** [comment]
just for the record: https://anaconda.org/conda-forge/torchmetrics
