### ISSUE TITLE
AveragePrecision returns list of metrics per class

### ISSUE THREAD

**Issue by jeweinb** [PyTorchLightning/metrics#471]
Why does AveragePrecision return many results per class when num_classes is specified? The other metrics such as Precision and Recall do not do this. This seems to be an inconsistency in the API.

https://github.com/PyTorchLightning/metrics/blob/master/torchmetrics/functional/classification/average_precision.py

**Comment by SkafteNicki** [comment]
Hi @jeweinb 
When setting `num_classes` argument the user can both be evaluating multi-class problems or multi-label problems. While we can agree that for multi-label problems we can take the average (macro, micro or weighted) of the individual scores and get a proper defined value. However, this does not hold for multi-class problems where we use a one-vs-the-rest approach, and in that case the average score is not well defined.

We can agree that this is a inconsistency in the API, and the way to solve it would be to introduce some `average` argument, but not sure if it is better to leave this to the user (based on the the aforementioned problems).

**Comment by jeweinb** [comment]
I'd say lets just treat it like the other scores. I would just expect all the classes to handle outputs the same way consistently. That way when I am coding I don't get different shapes of outputs from the metrics.
