### ISSUE TITLE
add option to automatically reset after compute.

### ISSUE THREAD

**Issue by cemde** [PyTorchLightning/metrics#482]
## 🚀 Feature

Add an argument to every Metric name `reset_on_compute`, e.g.

```python
acc = torchmetrics.Accuracy(num_classes=3, reset_on_compute=True)
```

would lead to something like 

```python
class Accuracy(Metric):
     def compute(self):
          acc = _accuracy(...)
          if self.reset_on_compute:
               self.reset()
          return acc
```

### Motivation
`torchmetrics` used to automatically call `reset` on `compute` (if I am not mistaken). Now it is a bit of work to call `reset` for every metric at the right point (given different values for compute_on_step per metric family / split) - even using `reset` on metric collections.

The state of the metrics fill up and cost quite a lot of GPU memory in larger projects. Having the option to discard everything after each compute automatically, would reduce storage required while keeping the code clean.

### Pitch

N/A

### Alternatives

Would be to keep calling `reset()` manually for everything.

### Additional context

N/A

**Comment by Borda** [comment]
@cemde mind check and comment on this re-design #344
