### ISSUE TITLE
`torchmetrics.F1` bug with `ignore_index` and macro averaging

### ISSUE THREAD

**Issue by ashispati** [PyTorchLightning/metrics#486]
## 🐛 Bug

An error is raised while using `torchmetrics.F1` if:  
1) `ignore_index` set to a valid class index (< `num_classes`)
2) `average = "macro" 
2) one of the non-ignored classes has no positive values in the target array

### To Reproduce

Run the following code:

```python
from torchmetrics import F1
import torch 

target = torch.tensor([0, 0, 0, 0])
preds = torch.tensor([0, 0, 0, 0])

# case 1: not using `ignore_index`
f1 = F1(num_classes=3, average="macro")
f1(preds, target)  # output:  tensor(1.)

# case 2: using `ignore_index`
f1 = F1(num_classes=3, average="macro", ignore_index=2)
f1(preds, target)  # raises Error
```

The following error in raised in `torchmetrics/functional/classification/f_beta.py`:
`line 100, in _fbeta_compute
    num[ignore_index, ...] = -1
IndexError: index 2 is out of bounds for dimension 0 with size 2`

### Expected behavior

The result in the above example should be the same as the case with no `ignore_index` provided. 

### Environment

- PyTorch Version (e.g., 1.0): `1.8.1`
- Python version: `3.6.12`
- CUDA/cuDNN version: NA
- GPU models and configuration: NA
- torchmetrics version: `0.5.0`

**Comment by SkafteNicki** [comment]
Hi @ashispati,
I created PR #495 that should fix the issue.
