### ISSUE TITLE
Support `sacrebleu` implementation under the `BLEUScore` metric

### ISSUE THREAD

**Issue by stancld** [PyTorchLightning/metrics#487]
## 🚀 Feature

Adjust the `BLEUScore` metric to support `sacrebleu` implementation from https://github.com/mjpost/sacrebleu.

### Motivation

In the paper ([Post, 2018](https://aclanthology.org/W18-6319.pdf)), it was demonstrated the reported research results can significantly vary based on different text tokenization and normalization strategies used for BLEU calculation. As the `sacrebleu` implementation is widely used, it would be nice to adapt the current implementation to support the core `sacrebleu` functionality (e.g. tokenization used by WMT).

### Additional context

I'll be happy to work on this if a consensus is found.

**Comment by SkafteNicki** [comment]
@stancld sound like a great enchancement, please feel free to send a PR :]
Just to understand this correctly, it is not a different metric but instead a adjusted version of the original?

**Comment by stancld** [comment]
@SkafteNicki  Yes, it's a standard bleu score. But it, for example, differs in tokenization :)

**Comment by stancld** [comment]
@SkafteNicki FYI, I will have a look at this issue tomorrow and send a draft PR :) (has been busy with finishing papers)

**Comment by stancld** [comment]
@SkafteNicki I found out `SacreBLEU` seems to actually differ from the bleu score implemented in the `NLTK` package. 

Example:
```python
from nltk.translate.bleu_score import corpus_bleu
from sacrebleu.metrics import BLEU

# Example from metrics tests
translate_corpus = [
    "It is a guide to action which ensures that the military always obeys the commands of the party"
]
reference_corpus = [
    [
        "It is a guide to action that ensures that the military will forever heed Party commands",
        "It is a guiding principle which makes the military forces always being under the command of the Party",
        "It is the practical guide for the army always to heed the directions of the party",
    ]
]

translate_corpus_split = [sentence.split() for sentence in translate_corpus]
reference_corpus_split = [[sentence.split() for sentence in reference] for reference in reference_corpus]

nltk_score = corpus_bleu(reference_corpus_split, translate_corpus_split)
sacre_bleu = BLEU(tokenize="none")  # tokenized using .split()
sacrebleu_score = sacre_bleu.corpus_score(translate_corpus, reference_corpus)

print(nltk_score)
print(sacrebleu_score)
```

```
>>> 0.5045666840058485
>>> BLEU = 41.18 61.1/47.1/37.5/26.7 (BP = 1.000 ratio = 1.125 hyp_len = 18 ref_len = 16)
```

I'll have a look at where these two metrics differ and if it's possible to make these two metrics compatible withinin a single `metrics` method/class.

**Comment by SkafteNicki** [comment]
@stancld I am fine with this being two different metric if it is easier for you to deal with. As long as they produce the correct result :]

**Comment by stancld** [comment]
@SkafteNicki Yes, I guess it would be slightly better to have a separate class for `SacreBLEUScore` which will inherit from the `BLEUScore` class. (I started working on that now and can send a PR soon)

One question though. Consider we have three sentences `(1, 2, 3)` and two reference systems `(a, b)`. SacreBLEU expects reference corpus in the following order:
```python
reference_corpus = [[ref1_a, ref2_a, ref_3a], [ref1_b, ref2_b, ref3_b]]
```
while the `nltk` implementation expects:
```python
reference_corpus = [[ref1_a, ref1_b], [ref2_a, ref2_b], [ref3_a, ref3_b]]
```

Do you think we should try to stick to the original implementation or rather try to unify this pattern? Thanks :)

**Comment by SkafteNicki** [comment]
@stancld sounds good :]

I think one of torchmetrics best features is that it is fairly unified e.g. all metrics basically take in a `pred` and `target` argument (even across domains). Therefore, i would prefer we keep this pattern .
