### ISSUE TITLE
MinMaxMetric for wrapping other metrics

### ISSUE THREAD

**Issue by janhenriklambrechts** [PyTorchLightning/metrics#49]
### Motivation

- `MinMaxMetric` is a metric that simply wraps another metric (e.g.`val_acc`) and creates a new metric that tracks the `min`, `max`  or both values of `val_acc`. 

### Pitch

- I personally use it to quickly see the `max_val_acc` of a complete experiment in TensorBoard (instead of going through the graph manually to find the max value) but I can see other usecases as well. 
- It was discussed in the PL Slack [here](https://pytorch-lightning.slack.com/archives/CU5PF2E2J/p1614602988020800) and clearly resonated with more users

### Additional context
- Happy to submit a PR for this feature, as I do have already a (incomplete) `MaxMetric` code implemented [here](https://gist.github.com/janhenriklambrechts/67a0faf5dc05d4e8d4d16973d1c03929)

**Comment by SkafteNicki** [comment]
Hi @janhenriklambrechts are you still interested in sending a PR for this feature?

**Comment by janhenriklambrechts** [comment]
Absolutely, you can assign it to me. 
Think I will be able to start working on it in a few days :)

**Comment by SkafteNicki** [comment]
@janhenriklambrechts Nice :]
Feel free to ping if you have any question (here or on slack).
If you need inspiration, then I have a open PR for another wrapper metric (https://github.com/PyTorchLightning/metrics/pull/101) for creating bootstrapped versions of metrics.

**Comment by janhenriklambrechts** [comment]
Thank you so much for the inspiration! Very useful!

**Comment by janhenriklambrechts** [comment]
Will only be able to work on it from beginning of July onward @SkafteNicki - is that OK?

**Comment by Borda** [comment]
> Will only be able to work on it from beginning of July onward @SkafteNicki - is that OK?

that is great! looking forward :rabbit:

**Comment by SkafteNicki** [comment]
@janhenriklambrechts any updates on this? :]

**Comment by janhenriklambrechts** [comment]
Hi @SkafteNicki, completely lost track of this - I am starting this weekend! Thanks for pinging me :)

**Comment by SkafteNicki** [comment]
@janhenriklambrechts no problem. Let me know if you need any help :]

**Comment by nils-werner** [comment]
Right now I can't log this if it is inside a `MetricCollection()`, right?

```python
self.val_metric = torchmetrics.MetricCollection({
    'acc': torchmetrics.Accuracy(),
    'acc_best': torchmetrics.MinMaxMetric(torchmetrics.Accuracy())
})
```

because `.compute()` will return

```
{'acc': tensor(0.9497), 'acc_best': {'raw': tensor(0.9595), 'max': tensor(1.), 'min': tensor(0.8281)}}
```

and I get an error message

```
ValueError: `self.log(val, {'acc': tensor(0.9497), 'acc_best': {'raw': tensor(0.9595), 'max': tensor(1.), 'min': tensor(0.8281)}})` was called, but nested dictionaries cannot be logged
```

It would be great if we could have a `MaxMetric()` wrapper that simply returns the max value, so that `.compute()` returns

```
{'acc': tensor(0.9497), 'acc_best': tensor(1.)}
```
