### ISSUE TITLE
Replace remaining docs links

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/metrics#504]
## 🚀 Feature

find remaining links in docstrings and replace them with global links
1. find all links in docstrings
2. create an entry in https://github.com/PyTorchLightning/metrics/blob/master/docs/source/links.rst
3. replace the docstring with this global

### Motivation

prune duplicates

### Pitch

finis docs unifications

**Comment by XFarooqi** [comment]
I have two questions and will be thankful for an appropriate answer.
1. What about the links in inline comments, should I add them too?
2. Can you please elaborate the term "additional context".

**Comment by XFarooqi** [comment]
### I have two questions and will be thankful for an appropriate answer.
1. What about the links in **Inline comments**, should I add them too?
2. Can you please elaborate the term **Additional context**.

**Comment by Borda** [comment]
> * What about the links in **Inline comments**, should I add them too?

no, let's keep comments as they are not mostly used in docs
(the special vase are comments which are starting with `#: `)

> * Can you please elaborate the term **Additional context**.

heh, I am not much aware of any, that came from the issue template :D

**Comment by SkafteNicki** [comment]
Fixed by #518.
