### ISSUE TITLE
ValueError: transformers.__spec__ is None

### ISSUE THREAD

**Issue by Ierezell** [PyTorchLightning/metrics#507]
## 🐛 Bug
When importing `torchmetrics`, it imports `transformers` which doesn't have the`__spec__` attribute and raises a `ValueError: transformers.__spec__ is None`

The problem have been raised here https://github.com/huggingface/transformers/issues/12904 and should be fixed here https://github.com/huggingface/transformers/pull/13321 

Could we update torchmetrics requirements or fix this error ? 

### To Reproduce

1. import torchmetric

### Expected behavior

Being able to import the module 

### Environment

- PyTorch Version (e.g., 1.0): 1.9.0
- transformers version : 4.9.2
- OS (e.g., Linux): Archlinux 5.13.13
- How you installed PyTorch (`conda`, `pip`, source): pip (poetry)
- Python version: 3.9.6 (same problem with 3.7)

### Additional context
Adding 
```
except ValueError: 
    return True
```
in `torchmetrics/utilities/import.py`
Makes everything works as usual (quick fix)

Thanks in advance, 
Have a great day.

**Comment by ronghanghu** [comment]
I'm also seeing the same error. I had to manually patch the transformers package according to https://github.com/huggingface/transformers/pull/13321

**Comment by Ierezell** [comment]
I can confirm that updating `transformers` to ` 4.10.2` solve the issue.
