### ISSUE TITLE
[Metrics] ROUGE

### ISSUE THREAD

**Issue by justusschock** [PyTorchLightning/metrics#51]
## 🚀 Feature
Implement ROUGE

**Comment by carmocca** [comment]
@SeanNaren you could take this at some point, as you already have a working implementation relying on https://pypi.org/project/rouge-score/

**Comment by SkafteNicki** [comment]
Copy implementation from here:
https://github.com/PyTorchLightning/lightning-flash/blob/master/flash/text/seq2seq/summarization/metric.py

**Comment by randolph-john** [comment]
A word of caution, the PyTorchLightning implementation of Rouge does not give the same results as the original PERL script. See here: https://github.com/google-research/google-research/issues/239. We also encountered this issue internally at Facebook.

**Comment by Borda** [comment]
@ananyahjha93 any update here? :rabbit:

**Comment by SkafteNicki** [comment]
@Borda if I am not wrong, @karthikrangasai would like to work on this issue when his Bleu PR has landed

**Comment by karthikrangasai** [comment]
@SkafteNicki yeah sure. I would like to work on this issue.
