### ISSUE TITLE
Add MS-SSIM

### ISSUE THREAD

**Issue by hodgka** [PyTorchLightning/metrics#522]
MS-SSIM is used quite frequently in tasks that compare image quality, such as deep image compression.

[Original paper](https://ece.uwaterloo.ca/~z70wang/publications/msssim.html)
[PyTorch Implementation](https://github.com/jorge-pessoa/pytorch-msssim)

There are also existing implementations in libraries like [scikit-video](http://www.scikit-video.org/stable/modules/generated/skvideo.measure.msssim.html) and [tensorflow](https://www.tensorflow.org/api_docs/python/tf/image/ssim_multiscale).

I'd be happy to work on this.

**Comment by SkafteNicki** [comment]
Hi @hodgka, sounds like a great addtion :]
Would you be up for sending a PR?

**Comment by stancld** [comment]
Is there any update on this? I'll be glad to have a look if it's still unassigned. :]
