### ISSUE TITLE
`_ssim_compute` creates extra tensors

### ISSUE THREAD

**Issue by manipopopo** [PyTorchLightning/metrics#529]
## 🐛 Bug

https://github.com/PyTorchLightning/metrics/blob/d354b7e30d3d0d4dbf9ea67f27d29f011670e2eb/torchmetrics/functional/image/ssim.py#L157

`output_list[5:]` are all unused empty tensors.

### To Reproduce

```python
import torch
from torchmetrics import functional

# ``_ssim_compute`` will create 2555 empty tensors in ``output_list``.
functional.ssim(torch.rand(512, 1, 17, 17), torch.rand(512, 1, 17, 17))
```

### Expected behavior

No extra tensors are created.

### Environment

- PyTorch Version (e.g., 1.0): 1.9.0
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version: 3.7.3
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

### Additional context

Maybe we could change

https://github.com/PyTorchLightning/metrics/blob/d354b7e30d3d0d4dbf9ea67f27d29f011670e2eb/torchmetrics/functional/image/ssim.py#L157

to
```python
output_list = [outputs[x * preds.size(0) : (x + 1) * preds.size(0)] for x in range(5)] 
```

or

```python
output_list = outputs.split(preds.size(0))
```

**Comment by SkafteNicki** [comment]
Hi @manipopopo, thanks for reporting this.
I created PR #539 that should fix it (thanks for the proposal) :]
