### ISSUE TITLE
How to get the iou of each class?

### ISSUE THREAD

**Issue by zsc1104** [PyTorchLightning/metrics#532]
If I have 5 classes , I want to get the iou of each class , like the following code to get the acc of each class , how to use the torchmetrics.IoU ?
torchmetrics.Accuracy(num_classes=num_classes, average='none')

**Comment by SkafteNicki** [comment]
Hi, by setting the `reduction` parameter you can achieve this:
```python
metric=IoU(num_classes=5, reduction='none')
target = torch.randint(0, 5, (10, 25, 25))
pred = torch.randint(0, 5, (10, 25, 25))
metric(pred, target)
tensor([0.1193, 0.1064, 0.1154, 0.1061, 0.1216])
```
Closing issue.
