### ISSUE TITLE
Implementing Normalized Discounted Cumulative Gain (NDCG)

### ISSUE THREAD

**Issue by jiwidi** [PyTorchLightning/metrics#550]
## 🚀 Feature

I want to implement a new metric( Normalized Discounted Cumulative Gain@K) used in information retrieval systems. I have used it for long in recommender systems, and it can expand the metrics capabilities. I'm reaching to the metrics team to validate the idea before working on it.

### Motivation

Normalized Discounted Cumulative Gain (NDCG)@K is a common metric for recommender systems. It comes from retrieval information systems and is close to HR@K but also looking at the position within your TOP K output. Hit ratio at K only checks if the target is within the top K recommended classes. NDCG takes into account what position within K was it found, higher values if 1 and lowest at K.

It is a common metric in academia, and it will help expand the usage of torch metrics package.

### Pitch

I would like to implement this metric and add it to repo, I'll work on it and create a PR. Im checking first for an initial approval.

Description of the metric: https://en.wikipedia.org/wiki/Discounted_cumulative_gain (see the normalized version)

**Comment by SkafteNicki** [comment]
Hi @jiwidi, if I am not mistaken we already have that metric in torchmetrics:
https://torchmetrics.readthedocs.io/en/latest/references/modules.html#retrievalnormalizeddcg
Please confirm this is the one :]

**Comment by jiwidi** [comment]
> Hi @jiwidi, if I am not mistaken we already have that metric in torchmetrics:
> 
> https://torchmetrics.readthedocs.io/en/latest/references/modules.html#retrievalnormalizeddcg
> 
> Please confirm this is the one :]

Yes your are right. My bad I missed it! I have been using custom code when it was already in the library 😓. 

Thank you!
