### ISSUE TITLE
Some metrics return NaN for edge cases

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/metrics#56]
### To Reproduce

https://github.com/PyTorchLightning/pytorch-lightning/blob/74171efadf5ea94416d26f1e2c27c1586a3a84b3/pytorch_lightning/metrics/classification/average_precision.py#L71

### Expected behavior

Some metrics for unused classes return NaN, I would say it shall be rather 0

**Comment by edenlightning** [comment]
@SkafteNicki is this still relevant?

**Comment by SkafteNicki** [comment]
Closing this as the general consensus in other frameworks is that it should map to nan in these specific cases (makes sense as the score is undefined and not "just" 0). 
Lets re-open if a user comes up with a specific use case where it may be beneficially to map to 0 instead.
