### ISSUE TITLE
Some metrics don't work on CPU using float16

### ISSUE THREAD

**Issue by Llannelongue** [PyTorchLightning/metrics#57]
## 🐛 Bug

It looks like some metrics such as Precision-Recall curve don't work on CPUs when using `float16`, perhaps due to a missing feature in pytorch? 

## Please reproduce using the BoringModel

https://colab.research.google.com/drive/1xDv043rRi5WBshP4m5aoxTt2ChlfxjIk?usp=sharing

### Expected behavior

the metrics should work in half precision on CPUs as well.

### Environment
* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.4
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu101
	- pytorch-lightning: 1.1.2
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           PyTorchLightning/pytorch-lightning#1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by edenlightning** [comment]
looks like this was fixed in https://github.com/pytorch/pytorch/commit/5d93e2b8180a495b6e78467ac470758134aac983
