### ISSUE TITLE
Typo in CalibrationError metric docs

### ISSUE THREAD

**Issue by edwardclem** [PyTorchLightning/metrics#596]
I just noticed typos in the CE metrics - the max calibration error and RMS calibration error labels should be switched, and there's a square root sign missing from the root mean squared error (whoops). That's my mistake, I'll submit a PR to fix.

**Comment by Borda** [comment]
Pls send a PR =)

**Comment by Borda** [comment]
@edwardclem still interested in sending the PR?

**Comment by edwardclem** [comment]
Whoops, let this slip! Yup, I'll fix it up and submit one ASAP.
