### ISSUE TITLE
Inconsistent input for BLEUScore compared to other metrics

### ISSUE THREAD

**Issue by stancld** [PyTorchLightning/metrics#600]
## 🚀 Enhancement

All text metrics except for `BLEUScore` expects input references and hypotheses are not tokenized. On the other hand, `BLEUScore` expects input sentences to be tokenized. I think it would be nice to unify the way of how sentences are passed in for the metrics calculation => all text metrics can be designed to receive non-tokenized input.

### Motivation

Unify the way of how the input sentences are passed in the NLP metrics.

**Comment by Borda** [comment]
Yeah, that would be great to unify :]

**Comment by stancld** [comment]
@Borda Maybe a good PR for supervision in #new_contributors as this is a nice way for someone of how to familiarize themselves with a variety of NLP metrics? :]

**Comment by mrleu** [comment]
Hello there! Just saw this on #new_contributors, and would love to work on this!

**Comment by mrleu** [comment]
Ready to review ^ Happy to accept any feedback!
