### ISSUE TITLE
Add a property to the Metric class from which can be determined if it can be self.log (scalar or not)

### ISSUE THREAD

**Issue by NumesSanguis** [PyTorchLightning/metrics#62]
## 🚀 Feature

Add a property to Metrics which can be checked to see if it can be logged or not.
Or better?, what the computed shape will be.

### Motivation

So far all Metrics in PL v1.0.x compute a scalar. The recommended way therefore is to call:
```python
metric(predictions, targets)
self.log("some_name", metric)
```
which has worked up until now.
However, with upcoming metrics like ConfusionMatrix, the computed value returned is not necessary a scalar, which will result in a ValueError when trying to log it.

If you have multiple metrics, code efficient would be to loop over the metrics, e.g.:
```python
for m in self.metrics:
    self.log("metric_name", m)
```
Adding a Metric that does not return a scalar will break this code.

### Pitch

These are some ideas, but probably there is something better.
- Add a property which can be checked against (e.g. scalar: True/False, loggable: True/False)
- Add a computed_shape property, so we can check if the computed value is either `(1, )` or `1`
- Add some new logic to `self.log()` to deal with non-scalar Metrics.

### Alternatives

This is a solution that would likely work in most cases, except if on step compute is turned off:
```
metric(predictions, targets)
if val.numel() == 1:  # only scalars
    self.log("some_name", metric)
```

### Additional context

Related discussion on the PyTorch Lightning forums:
https://forums.pytorchlightning.ai/t/logging-a-tensor/320

@SkafteNicki

**Comment by SkafteNicki** [comment]
With the separation of metrics from lightning this feature does not really fit this package any more as it is lightning specific.
Closing it.
