### ISSUE TITLE
Devcontainer Support

### ISSUE THREAD

**Issue by twsl** [PyTorchLightning/metrics#620]
## 🚀 Feature

Enable Devcontainers, for a standardized development environment and the option to use codespaces. 

### Motivation

I hate setting up dev environments, especially if I can mess up something at some point.

### Pitch

Add Devcontainer files.

### Alternatives

Keep it as is.

**Comment by Borda** [comment]
could you please link some best-practice or tutorial for new users on how to use codespaces

**Comment by twsl** [comment]
[Devcontainers](https://code.visualstudio.com/docs/remote/containers) allows you to use docker containers to create reproducible development environments and removes the problems, that something doesn't run on your machine. [Codespaces](https://docs.github.com/en/codespaces) builds upon that and allows you to run a devcontainer on github, e.g. in case you want to edit something on the fly, but I'm not sure if it's still for free.
You just need VS Code and Docker and will be prompted to open the project in a devcontainer, when a configuration exists.
