### ISSUE TITLE
[New metric] Add `EED`

### ISSUE THREAD

**Issue by stancld** [PyTorchLightning/metrics#635]
## 🚀 Feature

Add `EED`, a text metric used for NMT evaluation.

**Sources:**
Paper - [EED: Extended Edit Distance Measure for Machine Translation](https://aclanthology.org/W19-5359.pdf)
[Repo](https://github.com/rwth-i6/ExtendedEditDistance)

### Motivation

Over the years a number of machine translation metrics have been developed in order to evaluate the accuracy and quality of machine-generated translations. Metrics such as BLEU and TER have been used for decades. However, with the rapid progress of machine translation systems, the need for better metrics is growing. This paper proposes an extension of the edit distance, which achieves better human correlation, whilst remaining fast, flexible and easy to understand. ([Stanchev et al., 2019](https://aclanthology.org/W19-5359.pdf))

**Comment by stancld** [comment]
I'll handle this :]

**Comment by Borda** [comment]
@mathemusician could you comment here so we can assign this issue to you... :rabbit:

**Comment by mathemusician** [comment]
I got this.
