### ISSUE TITLE
`log_dict` is missing `prefix` parameter that is mentioned in docs

### ISSUE THREAD

**Issue by rivi** [PyTorchLightning/metrics#64]
## 🐛 Bug

[`MetricCollection` documentation](https://pytorch-lightning.readthedocs.io/en/1.2.0/extensions/metrics.html#metriccollection) mentions using `self.log_dict(self.train_metrics, on_step=True, on_epoch=False, prefix='train')`. The `prefix` parameter doesn't seem to be present in `log_dict` function header.

### Expected behavior

`prefix` is most likely usable in this context, so this feature should be implemented. If not - the documentation should be fixed.

### Environment

 - Lightning Version: 1.2.0

**Comment by SkafteNicki** [comment]
@jspaezp please checkout the PR I have opened #70 to see if anything is missing :]

**Comment by jspaezp** [comment]
@SkafteNicki looks great! Amazing work! 

@uwaisiqbal (just mentioning you so you know it is getting merged)

**Comment by uwaisiqbal** [comment]
Awesome thanks for the update and for the amazing work!

**Comment by uwaisiqbal** [comment]
When is the update with the `prefix` arg going to be released? Also, the documentation for the `MetricCollections` is out of date where it mentions the `prefix` arg can be used when cloning the `MetricCollection` https://torchmetrics.readthedocs.io/en/latest/pages/overview.html#metriccollection
