### ISSUE TITLE
Devcontainer invalid format

### ISSUE THREAD

**Issue by twsl** [PyTorchLightning/metrics#648]
## 🐛 Bug

Property `image` is not allowed. The docker image cannot be directly specified inside the `devcontainer.json`.

### To Reproduce

1. Open devcontainer in vscode
2. Still builds from python devcontainer

### Expected behavior

Load pytorch lightning metrics devcontainer iamge.

### Environment

- PyTorch Version (e.g., 1.0): 1.10
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source):
- Python version: 3.9
- CUDA/cuDNN version: 11.5/8
- GPU models and configuration:
- Any other relevant information:

**Comment by justusschock** [comment]
According to https://code.visualstudio.com/docs/remote/devcontainerjson-reference it should be allowed to specify it like that. I just missed the comma in the end
