### ISSUE TITLE
Test all metrics on GPU

### ISSUE THREAD

**Issue by twsl** [PyTorchLightning/metrics#675]
## 🚀 Feature

Add an option to run tests on a single GPU.

### Motivation

Currently tests for metrics are usually run via  [`run_class_metric_test`](https://github.com/PyTorchLightning/metrics/blob/master/tests/helpers/testers.py#L391), which defaults to CPU if only a sinlge GPU is present. This can cause issues with CUDA to go into a release unnoticed.

### Pitch

Fix quietly switching to cpu even if ddp=False and GPUs are available.
Updating `run_class_metric_test` to test on single gpu, cpu and both using ddp if available/selected.

### Alternatives

Accept incomplete test coverage.

**Comment by SkafteNicki** [comment]
Hi @twsl,

All metrics should already run on single GPU:
https://github.com/PyTorchLightning/metrics/blob/d071eb2f1245112c599b7fe0d165b8ac55663083/tests/helpers/testers.py#L450

**Comment by twsl** [comment]
@SkafteNicki You are correct, this mistake on my end was probably caused by a reset of the devcontainer settings disabling the gpu and me then just carelessly checking the device value..
However these is still no option to test all four combinations (single and multi cpu,gpu). Depending on the machine configuration, some tests are never considered. I'd much rather see a dedicated skipped test, if the machine config doesn't allow something.

**Comment by SkafteNicki** [comment]
@twsl I see your point.
Any recommendation how to do this the most easy way?

**Comment by twsl** [comment]
@SkafteNicki the refered proposal takes care of the pytest arguments. Each method there accepts a device to run on. I just dont know if that option is already supported in the ddp implementation
