### ISSUE TITLE
Support for metric names

### ISSUE THREAD

**Issue by Phinnik** [PyTorchLightning/metrics#682]
## 🚀 Feature

First of all, thank you for developing this project!

My request is to support metrics name property for Metric class. I don't know if it is a feature or may be a bug fix.

### Motivation

I found, that if I want to use multiple *MultioutputWrapper* in my *MetricCollection* it throws the error `ValueError: Encountered two metrics both named MultioutputWrapper`

Here is the code snippet to reproduce it:

```python
from torchmetrics import MetricCollection, MeanSquaredError, MeanAbsoluteError, MultioutputWrapper


metrics = MetricCollection([
    MultioutputWrapper(MeanSquaredError(), 5),
    MultioutputWrapper(MeanAbsoluteError(), 5),
])

```

### Pitch

It happens because of these lines of code: https://github.com/PyTorchLightning/metrics/blob/master/torchmetrics/collections.py#L187-L189

It would be great to change it to something like:

```python
name = metric.name
 if name in self:
    raise ValueError(f"Encountered two metrics both named {name}")
``` 

So, for __init__ method of metric class it should be great to add a parameter *name* like that:
```python
class Metrics(ABC, Module):
    def __init__(
        self,
        name: str = None,
        ...
    ) -> None:
        super().__init__()
        self.name = name if name is not None else self.__class__.__name__  
```

### Alternatives

Alternatively, we are pushed to change the *\_\_class\_\_.\_\_name\_\_* of **MultioutputWrapper** class manually to prevent the error. But that looks really bad.

**Comment by SkafteNicki** [comment]
Hi @Phinnik,
We do not support specifically what you are asking for, but you can solve the problem you currently have by giving metrics as a dict instead of a list for `MetricCollection`. So instead of:
```python
metrics = MetricCollection([
    MultioutputWrapper(MeanSquaredError(), 5),
    MultioutputWrapper(MeanAbsoluteError(), 5),
])
```
you would do:
```python
metrics = MetricCollection({
    'mean_squared_error': MultioutputWrapper(MeanSquaredError(), 5),
    'mean_absolute_error': MultioutputWrapper(MeanAbsoluteError(), 5),
})
```
this will essentially set the `name` in the `MetricCollection` to whatever you want :]

**Comment by Phinnik** [comment]
Oh, thank you so much, sir. Probably, need to read documentation more attentively next time :)

**Comment by thomasahle** [comment]
It would be nice if MetricCollection used repr(metric) instead of classname(metric). This would allow the metric designer to come up with a useful name based on the parameters.
