### ISSUE TITLE
mAP metric crashes when there are no ground truth boxes

### ISSUE THREAD

**Issue by OlofHarrysson** [PyTorchLightning/metrics#683]
## 🐛 Bug

The `torchmetrics.detection.map` class crashes if there are no ground truth boxes.

### To Reproduce

Run the example below. Produces the error `IndexError: The shape of the mask [0] at index 0 does not match the shape of the indexed tensor [1, 0] at index 0`

#### Code sample
```py
import torch
from torchmetrics.detection.map import MAP

metric = MAP()

metric.update(
    [
        dict(boxes=torch.Tensor([[214.1500, 41.2900, 562.4100, 285.0700]]), scores=torch.Tensor([0.5]), labels=torch.IntTensor([4])),
    ],
    [
        dict(boxes=torch.Tensor([]), labels=torch.IntTensor([])),
    ],
)
metric.compute()
```

**Comment by fazzoni** [comment]
Hello, 
I', experiencing the same issue while using the `IntersectionOverUnion` metric (`from torchmetrics.detection import IntersectionOverUnion`) when `class_metrics` is enabled (`IntersectionOverUnion(class_metrics=True)`).


Produces the error `IndexError: The shape of the mask [0] at index 0 does not match the shape of the indexed tensor ... at index 0`
