### ISSUE TITLE
Split `text` metrics into `text` and `speech` metrics.

### ISSUE THREAD

**Issue by stancld** [PyTorchLightning/metrics#685]
## 🚀 Enhancement

Split `text` metrics into `text` and `speech` metrics.

### Motivation

Currently, both `text` and `speech` metrics are all stored under `text` metrics. However, I think there are some good reasons why they should/may be split into two categories:
1. Text and speech are two different modalities
2. For `text` metric evaluation, we allow evaluating a hypothesis against multiple references. However, there is always a single reference for speech.
3. Also I think it might be a bit confusing for newcomers into NLG/speech which metrics are used for which modality.

### Pitch

Split `text` metrics into `text` and `speech` metrics. Otherwise, leave everything as it is.

### Alternatives

Keep it as it is.

@Borda @SkafteNicki What do you think about it? :]

**Comment by Borda** [comment]
> Text and speech are two different modalities

could you pls elaborate more on the difference as we would also need to make such an explanation in docs...

**Comment by SkafteNicki** [comment]
Is there a difference between `speech` and `audio`?

**Comment by stancld** [comment]
It seems to me that, for now, `speech` metrics consume text inputs while `audio` ones consider tensor inputs

**Comment by Borda** [comment]
> `speech` metrics consume text inputs while `audio` ones consider tensor inputs

yeah, but if `speech` has input text, why not keep it as `text`?

**Comment by stancld** [comment]
@Borda I also see the difference that `text` predictions can be naturally compared against multiple references, which is not the case for `speech` (at least I guess)... However, I have no strong opinion on this for now so we can definitely leave it as it is :]

**Comment by Borda** [comment]
well, I think that with this we go into too many details and we could also talk about if binary and multi-label classification shall be in a single package... :rabbit: lest put it on hold and reopen later if we have more reasons for such split... :angel:

**Comment by stancld** [comment]
> well, I think that with this we go into too many details and we could also talk about if binary and multi-label classification shall be in a single package... 🐰 lest put it on hold and reopen later if we have more reasons for such split... 👼

yep, agree :]
