### ISSUE TITLE
Unify the input order for `text` (NLG) metrics

### ISSUE THREAD

**Issue by stancld** [PyTorchLightning/metrics#686]
## 🚀 Enhancement

Unify the input order for `text` (NLG) metrics

### Motivation

We aim to unify text (NLG) metrics in a way that all of them will allow evaluating a hypothesis against multiple references. Nonetheless, there remains another distinction as some metrics presume `preds, targets` input order, while some expect `targets, preds` order. With respect to the whole TM ecosystem, we will go with `preds, targets`.

### Pitch

Change input order for the following NLG metrics:
- `BLEUScore` - B.C (add a warning suggested [here](https://github.com/PyTorchLightning/metrics/pull/687#issuecomment-999781877))
- `CHRFScore` - non B.C. (a new metrics in `v0.7`)
- `SacreBLEUScore` - B.C (add a warning suggested [here](https://github.com/PyTorchLightning/metrics/pull/687#issuecomment-999781877))
- `TER` - non B.C. (a new metrics in `v0.7`)

Standardize naming convention to have: `predictions` and `targets` everywhere.

### Alternatives

Keep it as it is.

@SkafteNicki @Borda @ashutoshml

**Comment by Borda** [comment]
I would try to make it for this `0.7`

**Comment by SkafteNicki** [comment]
If this is as simple as changing the order in a couple of metrics, then lets fit it into `0.7`

**Comment by stancld** [comment]
Yes, I think it's a simple change that affects only `ROUGEScore` and `BERTScore`:]

**Comment by ashutoshml** [comment]
@stancld Incase you aren't working on this, I can take it up.

**Comment by stancld** [comment]
@ashutoshml I've been finishing some other stuff, so it'd be great if you can have a look! O:]

**Comment by SkafteNicki** [comment]
@stancld is there a reason why we should standardize to
`target, preds`
instead of
`preds, target`
as the remaining codebase?

**Comment by stancld** [comment]
And actually I see that in the TM version `0.6.x` there were only `BLEUScore` which had `target, preds` pattern

**Comment by ashutoshml** [comment]
Also, naming standardization would help
`targets` or `references`?
`preds' or 'hypothesis`?

I personally would prefer `references` and `predictions`.

**Comment by Borda** [comment]
I think that standardization would be needed, for example, if you have a collection and one of the metrics have its inputs in reverse order, could be bad...

**Comment by ashutoshml** [comment]
In case we decide on the order `targets, preds`, the current PR is ready for review. 
If `preds, targets`, we might need to change the requirements/description of the issue, and change all files, other than the ones I have currently changed.

**Comment by stancld** [comment]
@SkafteNicki So I guess we will go for `preds, targets` order for all metrics? :]
cc: @ashutoshml

**Comment by ashutoshml** [comment]
Slightly confused. 
What should be the final order then? `targets, preds` or `preds, targets`?

**Comment by stancld** [comment]
As also suggested in [#687](https://github.com/PyTorchLightning/metrics/pull/687#discussion_r773769245), we will go with `preds, targets`. I'll re-formulate the issue. Sorry for the confusion @ashutoshml :]

**Comment by ashutoshml** [comment]
@stancld Thanks for updating the issue. I'll start working on it this weekend.

**Comment by ashutoshml** [comment]
@stancld: Should I modify all the files in `torchmetrics/text` to have `predictions` and `targets` or only the ones you've mentioned in the description of this issue?

**Comment by mathemusician** [comment]
@ashutoshml @stancld Now I'm really confused. I thought it was `preds` and `targets`, not `predictions` and `targets`?

**Comment by ashutoshml** [comment]
@mathemusician Use `predictions` and `targets` as naming. 
The earlier comments were primarily for the order of inputs by the metrics.
