### ISSUE TITLE
Code example error for AveragePrecision and PrecisionRecallCurve

### ISSUE THREAD

**Issue by 2533245542** [PyTorchLightning/metrics#701]
## 📚 Documentation
In their binary case code examples, the `pred` inputs are integers, but shouldn't they be probabilities? 
<img width="575" alt="image" src="https://user-images.githubusercontent.com/28517073/147843097-ca5049ac-c3e0-4aa8-8988-b670552d1956.png">

Here is the scikit-learn counterpart, where probabilities are used.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/28517073/147843102-49a6ff01-ef44-4376-8432-ae3431ff574d.png">

**Comment by Borda** [comment]
yeah, it shall be named as multi-class or fix the prediction... are you interested in sending PR with a quick fix? :]

**Comment by jscottcronin** [comment]
@Borda - I'm looking to get more involved with contributions for pytorch lightning. Are you ok if I pick up this issue?

**Comment by jscottcronin** [comment]
There is already an example for multi class, so I went ahead and updated the documentation for the binary class to fix the prediction values as floats. Also updated the values of `precision`, `recall`, and `thresholds` to match the output and validated that the floats match that from sklearn. Will link to the PR once completed.

**Comment by jscottcronin** [comment]
Hmm, it looks like I also need to do this update for AveragePrecision
