### ISSUE TITLE
ImportError: cannot import name 'SDR' from 'torchmetrics.audio'

### ISSUE THREAD

**Issue by walidsst** [PyTorchLightning/metrics#703]
I have the following:
version : '0.6.2'
python: 3.7

```
from torchmetrics import audio
dir(audio)

['PESQ',
 'PIT',
 'SI_SDR',
 'SI_SNR',
 'SNR',
 'STOI',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'pesq',
 'pit',
 'si_sdr',
 'si_snr',
 'snr',
 'stoi']
```

Traceback (most recent call last):
  File "trainer.py", line 5, in <module>
    from train.train import Trainer
  File "/home/**/train.py", line 5, in <module>
    from torchmetrics.audio import SDR
ImportError: cannot import name 'SDR' from 'torchmetrics.audio' (/home/**/torch/lib/python3.7/site-packages/torchmetrics/audio/__init__.py)

**Comment by Borda** [comment]
@walidsst I think that you swapped it with Scale-invariant signal-to-distortion ratio (SI-SDR), checking the history and seems it was always `SI_SDR` not just `SDR`... cc: @quancs @SkafteNicki

**Comment by walidsst** [comment]
I found it in the docs of the package [here](https://torchmetrics.readthedocs.io/en/latest/references/modules.html#sdr) alsoo the sdr in functional doesn't exist but in docs exist check [here](https://torchmetrics.readthedocs.io/en/latest/references/functional.html#sdr-func)

**Comment by Borda** [comment]
ohh, I see now, the case is that it was added recently but it was not released yet...
you are referring to the **latest** docs not **stable**, so to get this metric you need to run 
```
pip install https://github.com/PyTorchLightning/metrics/archive/refs/heads/master.zip
```
 or wait for the next v0.7 release which is coming soon

**Comment by walidsst** [comment]
yeah I didn't know, I check the last released package it was as mine, thank you for the clarification.
