### ISSUE TITLE
Clean `text` tests - remove `input_order` argument

### ISSUE THREAD

**Issue by stancld** [PyTorchLightning/metrics#704]
## 🚀 Clean `text` tests - remove `input_order` argument

As we aim to unify `preds, target` order across the `text` package, we can remove the `input_order` argument from `torchmetrics.tests.text.helpers._class_test` and `torchmetrics.tests.text.helpers._functional_test` methods.

I can do that once #696 will be merged :]

cc: @Borda @SkafteNicki

**Comment by jscottcronin** [comment]
@stancld @Borda - I can take this one. Please assign to me?

**Comment by jscottcronin** [comment]
PR Created: https://github.com/PyTorchLightning/metrics/pull/717
