### ISSUE TITLE
ConfusionMatrix is float32 which gives slightly varying ground truth counts

### ISSUE THREAD

**Issue by mona0809** [PyTorchLightning/metrics#708]
## 🐛 Bug

confmat in ConfusionMatrix is of data type float32 (see: https://github.com/PyTorchLightning/metrics/blob/master/torchmetrics/classification/confusion_matrix.py#L121). This results in slightly varying ground truth counts when the confusion matrix contains a lot of values (e.g. for semantic segmentation):

### To Reproduce

```python
import torch
from torchmetrics import ConfusionMatrix

batchsize = 256
n_classes = 2
width = 512
height = 512

metric = ConfusionMatrix(num_classes=n_classes)

target = torch.randint(size=(batchsize, height, width), low=0, high=n_classes)

for i in range(10):
    preds = torch.randint(size=(batchsize, height, width), low=0, high=n_classes)
    metric.update(preds=preds, target=target)
    print(torch.sum(metric.confmat, axis=1))
    metric.reset()
```

The output is:

```bash
tensor([33556800., 33552060.])
tensor([33556804., 33552060.])
tensor([33556800., 33552060.])
tensor([33556804., 33552060.])
tensor([33556800., 33552060.])
tensor([33556804., 33552060.])
tensor([33556804., 33552060.])
tensor([33556804., 33552060.])
tensor([33556800., 33552060.])
tensor([33556804., 33552060.])
```

### Expected behavior

The number of ground truth pixels should not vary. When I change the data type of confmat to int, everything is fine.

### Environment

- PyTorch Version (e.g., 1.0): 1.10.0
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): conda
- Python version: 3.8

**Comment by Borda** [comment]
interesting, probably using float64 or uint64 would help... are you interested in sending fix? :rabbit:
