### ISSUE TITLE
Unify `preds, target` input arg naming across all `text` metrics

### ISSUE THREAD

**Issue by stancld** [PyTorchLightning/metrics#716]
## 🚀 Enhancement / API / design

Unify `preds, target` input argument naming across all `text` metrics.

Metrics:
- [x] `bert` #723
- [x] `bleu` #723
- [x] `cer` #727
- [x] `chrf` #723
- [x] `mer` #727
- [x]  `rouge` #727
- [x] `sacre_bleu` #723
- [x] `ter` #727
- [x] `wer` #727
- [x] `wip` #723
- [x] `wil` #723
- [x] `squad` #727

Additional context:

@ashutoshml and I will handle that.

**Comment by stancld** [comment]
@ashutoshml

**Comment by ashutoshml** [comment]
@stancld: Sounds good. I'll start working on `cer, ter, wer, sacrebleu, rouge, squad`

**Comment by Borda** [comment]
great work @stancld @ashutoshml! :tada:

**Comment by stancld** [comment]
@ashutoshml Thanks a lot for your contribution! O:]
