### ISSUE TITLE
Unify naming of domains

### ISSUE THREAD

**Issue by SkafteNicki** [PyTorchLightning/metrics#720]
## 📚 Documentation

In both the "Module metrics" and "Functional metrics" subsections we are inconsistent with how we have the domains:
They should either be just the domain name or have the "metrics" postfix. IMO it should just be the domain name.

![Screenshot 2022-01-06 at 11-19-19 Module metrics — PyTorch-Metrics 0 7 0dev documentation](https://user-images.githubusercontent.com/24896311/148376598-ee86fafc-c0fa-4379-9994-50e669ec6a90.png)

**Comment by AndresAlgaba** [comment]
I will fix this :)
