### ISSUE TITLE
reimplement PESQ

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/metrics#726]
## 🚀 Feature

reduce dependency and ideally implement it with Pytorch

### Motivation

preferable in-house solution...
there is some strange collision between `pesq`
https://github.com/ludlows/python-pesq/blob/05f835a196ea1aea01e6d7e51c38a242e9049b64/setup.py#L46
and used `pycocotools` for testing
https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/setup.py#L20-L24

### Additional context

https://github.com/PyTorchLightning/metrics/pull/725#issuecomment-1006913105

**Comment by quancs** [comment]
I'm not sure if it legal to do so... Seems the pesq is owned by some organization

https://github.com/ludlows/python-pesq/blob/master/pesq/dsp.h

**Comment by SkafteNicki** [comment]
Agree with @quancs, the text is pretty clear:
```
RESTRICTIONS:
-------------
The user cannot:
1.	alter, duplicate, modify, adapt, or translate in whole or in
      part any aspect of the PESQ Algorithm and or PESQ Software
2.	sell, hire, loan, distribute, dispose or put to any commercial
      use other than those permitted below in whole or in part any
      aspect of the PESQ Algorithm and or PESQ Software
```
we would violate 1. Closing issue.

**Comment by Borda** [comment]
Well, how about we implement it purely in Python/PyTorch no compiled C code?

**Comment by Borda** [comment]
just for the record... 841
