### ISSUE TITLE
Improve doctests - conditional dependency skip

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/metrics#733]
## 🚀 Feature

use conditional skip for doctest which are showing metrics with additional dependency
Thx @ethanwharris for finding this nice pytest extension - `pytest-doctestplus`
see sample usage: https://github.com/astropy/pytest-doctestplus#doctest-dependencies

### Motivation

have all doctests/examples tested again

### Pitch

At this moment we are skipping all which are not pure PyTorch so the outputs could be wrong after several changes in codebase

**Comment by ethanwharris** [comment]
This is how we do it in Flash:
```
# Skip doctests if requirements aren't available
if not _IMAGE_AVAILABLE:
    __doctest_skip__ = ["ImageClassificationData", "ImageClassificationData.*"]
```
Then enable pytest-doctestplus in `setup.cfg` with `doctest_plus = enabled`

**Comment by stancld** [comment]
@Borda Is there any help needed to finish `v0.7`? :]

**Comment by Borda** [comment]
> @Borda Is there any help needed to finish `v0.7`? :]

It would be nice, but not rush with this one =)
