### ISSUE TITLE
use `FutureWarning` for deprecations

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/metrics#744]
## 🚀 Feature

see suggestion in https://github.com/PyTorchLightning/metrics/pull/740#discussion_r782088021

### Motivation

most of the deprecations in TM are meant to users not developers

### Additional context

- **exception `DeprecationWarning`** Base class for warnings about deprecated features when those warnings are **intended for other Python developers**. _Ignored by the default warning filters_, except in the `__main__` module (PEP 565). Enabling the Python Development Mode shows this warning.

- **exception `FutureWarning`** Base class for warnings about deprecated features when those warnings are **intended for end users of applications** that are written in Python.

**Comment by jscottcronin** [comment]
@Borda - I can take this issue.

As I understand, I will convert `DeprecationWarning` objects to `FutureWarning` in PR: https://github.com/PyTorchLightning/metrics/pull/740

Correct?

**Comment by Borda** [comment]
@jscottcronin lets wait till all deprecation lands, and then I think it ll be updating stream in #745

**Comment by Borda** [comment]
can you make it today so we can shoot the final release soon after?

**Comment by jscottcronin** [comment]
@Borda No problem, working on it now.

**Comment by daniellepintz** [comment]
Should we do the same for Lightning?
