### ISSUE TITLE
Prune deprecated metrics

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/metrics#771]
## 🚀 Feature

Remove all deprecated metrics, lets group this cleaning per domain:
- [x] audio #805
- [x] image #796
- [x] classification & regression #806
- [x] detection & pairwise #804
- [x] text #773

**Comment by ashutoshml** [comment]
@Borda Can help with text

**Comment by Borda** [comment]
@ashutoshml would you take some more? :rabbit:

**Comment by ashutoshml** [comment]
@Borda Done. Please check. 
Integration test is failing for #806 for `python 3.6`. Not sure how to resolve it.

**Comment by ashutoshml** [comment]
@Borda Please check #804  and #805 as well.

**Comment by Borda** [comment]
@ashutoshml very helpful, THANK YOU!

**Comment by ashutoshml** [comment]
Since all PRs have been merged, this issue can be closed :)
