### ISSUE TITLE
Add `RetrievalRecallAtFixedPrecision`

### ISSUE THREAD

**Issue by stancld** [PyTorchLightning/metrics#780]
## 🚀 Feature

Add a new metric calculating (retrieval) recall at K at fixed precision  (typically `K=1` for this case).

### Motivation

From my experience in IR, there are use cases when a user should be provided with some results on top position (e.g. featured snippets in google search) only with some precision threshold. Subsequently, one may be interested in the recall to know which portion of queries will be handled.

### Pitch

Add a new retrieval metric `RetrievalRecallAtFixedPrecision`, which is inspired by `BinnedRecallAtFixedPrecision` and `RetrievalPrecision`.

**Comment by MrShevan** [comment]
Can i get this assigned to me please?

**Comment by stancld** [comment]
@MrShevan Yes, of course, great! :] Feel free to open a draft PR and tag me there once you have anything ready
