### ISSUE TITLE
[Doc] Confusion in the torchmetric with lightning

### ISSUE THREAD

**Issue by edwardpwtsoi** [PyTorchLightning/metrics#793]
## 📚 Documentation

https://torchmetrics.readthedocs.io/en/stable/pages/lightning.html

In the second session, it stated that `Metric objects can also be directly logged in Lightning using the LightningModule self.log method. `

And I tried to log the MAP metric for object detection and it will resulted in an error which trying to call detach method of the return of the metric which indicated this metric actually could not be log with the self.log directly.

**Comment by SkafteNicki** [comment]
Hi @edwardpwtsoi , thanks for raising this issue and sending a PR :]
However, it seems that you have opened the PR in your own fork. Can you re-send to this repository?
