### ISSUE TITLE
re-implement SDR

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/metrics#803]
## 🚀 Feature

seems we start to have hanging tests with SDR, moreover `fast_bss_eval` is only v0.1
moreover checking some license discrepancies as TM uses apache and BSS is MIT

### Motivation

reduce dependencies :rabbit: 

### Alternatives

keep them only as a reference for testing

**Comment by quancs** [comment]
The slow tests may from the metric itself, not the implementation. 

It's a good idea to not depend on the external package `fast_bss_eval` for any possible imcompatible changes in future version of `fast_bss_eval`. For the licenses, if we use the code of `fast_bss_eval`, we need to put the MIT license at the head of that file?

**Comment by Borda** [comment]
> we need to put the MIT license at the head of that file?

I am rather thinking to implement it directly based on a paper like this one https://arxiv.org/pdf/1811.02508.pdf

**Comment by quancs** [comment]
> I am rather thinking to implement it directly based on a paper like this one https://arxiv.org/pdf/1811.02508.pdf

Well, seems the paper you refered to is si-sdr.
SDR is https://arxiv.org/abs/2110.06440, and fast_bss_eval is the official implementation of this paper.

**Comment by Borda** [comment]
> SDR is https://arxiv.org/abs/2110.06440, and fast_bss_eval is the official implementation of this paper.

unless they have an exclusive right on the SDR metric I think we are fine to implement it too and run tests against it so we can be sure we compute the correct values :)

**Comment by Abdelrhman-Hosny** [comment]
I would like to work on this.

I would be required to re-implement the functions that are imported from `fast_bss_eval` with my own, correct?

**Comment by quancs** [comment]
> I would like to work on this.
> 
> I would be required to re-implement the functions that are imported from `fast_bss_eval` with my own, correct?

You could refer to the [paper](https://arxiv.org/abs/2110.06440) of `fast_bss_eval`

**Comment by fakufaku** [comment]
Hi @Borda , I have fixed some of the bugs that caused the permutation solver to hang. I have also extended the compatibility back to pytorch 1.4. You may want to bump up the version and give it another go. For torch<=1.7 the package [torch_complex](https://github.com/kamo-naoyuki/pytorch_complex) is necessary.

**Comment by quancs** [comment]
Hi, @fakufaku your work is great! 
But the current implementation of `SDR` in `TorchMetrics` largely depends your inner functions in `fast_bss_eval` which might change in the future versions of `fast_bss_eval`. [inner functions used](https://github.com/PyTorchLightning/metrics/blob/5216c50ba4d1407aa039e6cbde390c07866ffc69/torchmetrics/functional/audio/sdr.py#L23-L37)

So, would you mind to implement the `SDR` in `TorchMetrics` natively and officially by you (as advised by @Borda) ^^ :

> I am rather thinking to implement it directly based on a paper like this one https://arxiv.org/pdf/1811.02508.pdf
