### ISSUE TITLE
The authors affiliation info is incomplete in paper.md

### ISSUE THREAD

**Issue by inpefess** [PyTorchLightning/metrics#807]
For more details see https://github.com/openjournals/joss-reviews/issues/4101#issuecomment-1022812990

**Comment by justusschock** [comment]
Hi @inpefess ,

Yes the author @maximsch2 chose not to have an affiliation. I asked the editor how to handle that (see https://github.com/openjournals/joss-reviews/issues/4101#issuecomment-1024121296)

**Comment by justusschock** [comment]
Fixed by #817
