### ISSUE TITLE
Missing DOI in paper.md

### ISSUE THREAD

**Issue by inpefess** [PyTorchLightning/metrics#809]
For more details please look [here](https://github.com/openjournals/joss-reviews/issues/4101#issuecomment-1022813164) and [here](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)

**Comment by justusschock** [comment]
Hi, Thanks a lot, I did look into this before and the missing doi is completely unrelated to the software it links it to. 

The doi seems to be part of an encyclopaedia explaining the term `keras`. The software is cited as suggested by the authors [here](https://keras.io/getting_started/faq/#how-should-i-cite-keras)
