### ISSUE TITLE
3D SSIM

### ISSUE THREAD

**Issue by weningerleon** [PyTorchLightning/metrics#812]
The metrics `StructuralSimilarityIndexMeasure` and `MultiScaleStructuralSimilarityIndexMeasure` current only support 2D image data. A 3D version would be nice to have, and an extension to allow 3D data should be straightforward to implement. If you are interested in such an extension, I could take over the implementation.

**Comment by Borda** [comment]
@weningerleon that would be a great addition, love to see your contributions! :rabbit:
cc: @SkafteNicki

**Comment by justusschock** [comment]
@weningerleon If you have a prototype, just open a PR and we can also see how we go there with testing

**Comment by weningerleon** [comment]
Opened a PR. :)
The implementation produces sensible results on my data. If there's any standard way of testing please let me know. Once this gets green light, I'll have a look at MultiScaleStructuralSimilarityIndexMeasure.
