### ISSUE TITLE
Micro Average IoU

### ISSUE THREAD

**Issue by razmikmelikbekyan** [PyTorchLightning/metrics#826]
## 🚀 Feature

It would be nice to have IoU accept parameters similar to Recall and Precision, in a way that we can able to calculate the micro average version as well. The current implementation is calculating the macro one when `reduction=elementwise_mean`.

**Comment by Borda** [comment]
Sounds interesting, do you want to send a PR for it?

**Comment by razmikmelikbekyan** [comment]
> Sounds interesting, do you want to send a PR for it?

with pleasure, will do during up coming days

**Comment by Borda** [comment]
@razmikmelikbekyan how is it going, have you had a chance to look at it? :rabbit:

**Comment by razmikmelikbekyan** [comment]
@Borda I did not have chance to look yet, but will try to do it in upcoming week.

**Comment by razmikmelikbekyan** [comment]
#874 PR is open
