### ISSUE TITLE
classwisewrapper doesn't support prefix

### ISSUE THREAD

**Issue by cnut1648** [PyTorchLightning/metrics#842]
## 🐛 Bug
Hi, good afternoon.

I have defined `ClasswiseWrapper` inside a `MetricCollection` which looks like this

```python
train_metrics = MetricCollection({
                # weighted acc
                "WA": Accuracy(num_classes=num_classes, threshold=0.5, average=avg),
                # unweight acc
                "UA": Accuracy(num_classes=num_classes, threshold=0.5, average="micro"),
                "Precision": Precision(num_classes=num_classes, threshold=0.5, average=avg),
                "Recall": Recall(num_classes=num_classes, threshold=0.5, average=avg),
                "UAR": Recall(num_classes=num_classes, threshold=0.5, average="micro"),
                # weighted F1
                "WF1": F1Score(num_classes=num_classes, threshold=0.5, average=avg),
                # unweight F1
                "UF1": F1Score(num_classes=num_classes, threshold=0.5, average="micro"),
                "MAE": MeanAbsoluteError(),
                "Corr": Corr(compute_on_step=False),
                "acc": ClasswiseWrapper(Accuracy(num_classes=num_classes, average=None), labels),
                "r": ClasswiseWrapper(Precision(num_classes=num_classes, average=None), labels),
                "p": ClasswiseWrapper(Recall(num_classes=num_classes, average=None), labels),
                "f1": ClasswiseWrapper(F1Score(num_classes=num_classes, average=None), labels),
            }, prefix="train/epoch/")
```
But it seems that when I call
```
metrics = train_metrics.compute()
```
although I can get other metrics with prefix all right (e.g. `train/epoch/UF1`),classwisewrapper doesn't take prefix into account, and I get `acc_label1` `acc_label2` etc.

### Expected behavior

I think once classwisewrapper is inside a `MetricCollection` it should have something like `train/epoch/acc_label1`.

### Environment

- PyTorch Version (e.g., 1.0): 1.8.2
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): conda
- Python version: 3.7.11
- Any other relevant information: torch metrics install from lastest master (0.8.0.dev0)

### Additional context

Thank you for this awesome project!!

**Comment by SkafteNicki** [comment]
@cnut1648 thanks for reporting this. I take a look at it today (should be a simple fix). Great to know that the wrapper is useful to some users :]
