### ISSUE TITLE
Allow soft target labels for classification tasks

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/metrics#882]
## 🚀 Feature

if the target labels are float we will perform the thresholding with the same value as we use for predictions...

### Motivation

in principle, we shall be able to compute scores even for soft labels
In practice, I am trying Kaggle competition classifying birds in audion, but it also includes some birds in the background which could be labeled as 0.5 (half presented) needed for optimization but now not compatible with metrics...
https://www.kaggle.com/jirkaborovec/birdclef-eda-multi-class-flash-effnet

### Additional context

Flash with soft: https://github.com/PyTorchLightning/lightning-flash/pull/1210

Cc: @SkafteNicki @ethanwharris

**Comment by SkafteNicki** [comment]
@Borda this is duplicate of: https://github.com/PyTorchLightning/metrics/issues/449
Closing in favour of the old issue.
