### ISSUE TITLE
No difference between RougeL and RougeLsum

### ISSUE THREAD

**Issue by FeiWang96** [PyTorchLightning/metrics#904]
### To Reproduce

I finetune BART on CNN/DailyMail dataset using lightning transformers.

#### Code sample

https://github.com/PyTorchLightning/lightning-transformers/blob/master/lightning_transformers/task/nlp/summarization/model.py#L43

### Expected behavior

Each document and summary in CNN/DailyMail have multiple sentences, so RougeL and RougeLsum should be different.

### Environment

- OS (e.g., Linux): Linux
- Python & PyTorch Version (e.g., 1.0): Python 3.9, Pytorch 1.10
- How you installed PyTorch (`conda`, `pip`, build command if you used source): pip
- Any other relevant information:

### Additional context

I've checked the [code](https://github.com/PyTorchLightning/metrics/blob/master/torchmetrics/functional/text/rouge.py#L162) for computing  RougeL and RougeLsum. 
It seems that the only difference is that a separator '\n' is inserted after each sentence when calculating RougeLsum.
However, the '\n' is not treated as a special token when calculating lcs and the final score.

**Comment by SkafteNicki** [comment]
cc: @stancld
