### ISSUE TITLE
Rename detection map file 

### ISSUE THREAD

**Issue by OlofHarrysson** [PyTorchLightning/metrics#906]
## 🐛 Bug

The MeanAveragePrecision metric is located in a file `torchmetrics/detection/map.py`. If you want to import this file, you would write `from torchmetrics.detection import map`. This replaces the built-in map function which is not so pretty.

Changing this file would avoid this. I suggest mean_ap.py.

**Comment by Borda** [comment]
Good point, mind sending a PR? :rabbit: 
cc: @SkafteNicki

**Comment by SkafteNicki** [comment]
Fine by me :]

**Comment by OlofHarrysson** [comment]
PR ready https://github.com/PyTorchLightning/metrics/pull/908
@SkafteNicki @Borda
