### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'detach' for ROC when logging.

### ISSUE THREAD

**Issue by dreaquil** [PyTorchLightning/metrics#916]
## 🐛 Bug

Cannot log ROC using the pl module log method. What is the best way to go about returning the ROC metrics (FPR, TPR, Thresholds) from test?

### To Reproduce
```
  File "/Users/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 533, in _get_cache
    return cache.detach()
AttributeError: 'tuple' object has no attribute 'detach'
```
### Environment

- OS (e.g., Linux):
- Python & PyTorch Version (e.g., 1.0):
- How you installed PyTorch (`conda`, `pip`, build command if you used source):
- Any other relevant information:

**Comment by SkafteNicki** [comment]
Hi @dreaquil,
`self.log` only supports logging of *scalar* tensors (documented [here](https://torchmetrics.readthedocs.io/en/latest/pages/lightning.html#logging-torchmetrics)). For metrics that do not return scalar tensors, the logging will depend on the specific metric.
For ROC metric i would personally render the results as a figure (probably using [RocCurveDisplay](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.RocCurveDisplay.html#sklearn.metrics.RocCurveDisplay.from_estimator) from sklearn) and then log the figure. How to log a figure in lightning depends on what logger you are using. Again, personally I use wandb and in that case I would log the figure using
```python
self.logger.experiment.log({"key": wandb.Image(figure)})
```

**Comment by dreaquil** [comment]
Hi @SkafteNicki,
Thanks for the suggestion!
