### ISSUE TITLE
Update the PDF

### ISSUE THREAD

**Issue by rasbt** [PyTorchLightning/metrics#925]
## 📚 Documentation

I got some feedback from a colleague that the PDF is out of date and points to version 0.2. I don't even know where to find the PDF, lol.

I see two ways we can handle this

a) Remove the PDF and links to the PDF (assuming that no one will miss them)

b) Fix the PDF and add this as a automated step to the build process.

**Comment by SkafteNicki** [comment]
Hi @rasbt,
What PDF is you referring to?

**Comment by rasbt** [comment]
This one here: https://torchmetrics.readthedocs.io/_/downloads/en/v0.2.0/pdf/
Not sure how my friend found it haha

**Comment by Borda** [comment]
well if you request a pdf of version `v0.2.0` it is quite natural that you get such docs/PDF :)
try the correct - https://torchmetrics.readthedocs.io/_/downloads/en/stable/pdf/

**Comment by rasbt** [comment]
We had this discussion on Slack so you probably fixed it in the meantime 😉. Is this part of the version release process now to ensure that stable is always up to date?

**Comment by Borda** [comment]
> Is this part of the version release process now to ensure that stable is always up to date?

I had not touch anything, it was there all the time... so rather the question is how the person got to the strange/old link :thinking:
