### ISSUE TITLE
Using Module Metrics with PyTorch DDP (without PyTorch Lightning)

### ISSUE THREAD

**Issue by Alec-Stashevsky** [PyTorchLightning/metrics#938]
## 🐛 Bug

I have a base PyTorch model that I implement distributing training using `torch.nn.parallel.DistributedDataParallel.` I only perform evaluation on a single GPU. 

I have a `MetricCollection` that I use to calculate metrics during test time. I only run the test function on a single GPU (rank 0), however, I train on multiple GPUs using the base PyTorch `DistributedDataParallel` wrapper:

```
from torch.nn.parallel import DistributedDataParallel as DDP
model = DDP(model, broadcast_buffers=False)
```

The issue is when I call metrics.compute() at the end of the testing, torchmetrics attempts to perform a distributed synchronization process across all GPUs (by default, `torch.distributed.all_gather()`). Because the test function is only called if the process is of rank 0, there are no tensors to gather from the additional GPUs and the code just hangs at the compute step until the timeout is hit with the error message:

Timeout: A call to 'allGather' has taken over 300.000000 seconds. Terminating the distributed job.

### To Reproduce
```py
import os
import sys
import tempfile
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.optim as optim
import torch.multiprocessing as mp
from torch.nn.parallel import DistributedDataParallel as DDP

def setup(rank, world_size):
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'

    # initialize the process group
    dist.init_process_group("gloo", rank=rank, world_size=world_size)

def cleanup():
    dist.destroy_process_group()

def test(model, data):

   metrics = torchmetrics.Accuracy()

   for i in data:
        preds = model(i)
        targets =  i.targets
        batch_metrics = metric(preds, i.targets)
   
   test_results = metrics.compute()   #this is the point where the code hangs if the model is DDP

   metrics.reset()
       
   return test_results

class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(10, 10)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(10, 5)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))

setup(rank, world_size)
# create model and move it to GPU with id rank
model = ToyModel().to(rank)
ddp_model = DDP(model, device_ids=[rank])
loss_fn = nn.MSELoss()
optimizer = optim.SGD(ddp_model.parameters(), lr=0.001)

optimizer.zero_grad()
outputs = ddp_model(torch.randn(20, 10))
labels = torch.randn(20, 5).to(rank)
loss_fn(outputs, labels).backward()
optimizer.step()

if torch.distributed.get_rank() == 0:
    test(model=ddp_model, data=torch.randn(20, 10))
```

### Expected behavior

I would expect for the torchmetrics module be able to only look at a given process. Or to be easily able to select which GPUs or processes I want to aggregate from.

### Environment

- OS: Linux
- Python & PyTorch Version: 1.10
- How you installed PyTorch: `conda`:
- Any other relevant information:

### Additional context

I have tried initializing the metrics as part of the PyTorch module, or directly in the test loop (as I show above) but both fail for the same reason. When I evaluated the test set across all GPUs (but do not use a distributed sampler), the .compute() step completed successfully, because it was able to gather identical tensors from all GPUs as they all were sent the entire and identical test data. Having to do this is not ideal.

**Comment by kuntiik** [comment]
I am facing the same issue even with pytorch-lightning. The code is stuck at MeanAveragePrecision.compute(). Should I open a new issue?

**Comment by Alec-Stashevsky** [comment]
@SkafteNicki I seem to be having trouble using this. I use SageMaker to train, so I have the following code in my train.py:

```
from torch.distributed import init_process_group
import smdistributed.dataparallel.torch.torch_smddp

init_process_group(backend='smddp')

# From the above code snippet I provided ^
if torch.distributed.get_rank() == 0:
    test(model=ddp_model, data=torch.randn(20, 10)
```

This creates a process_group for the entire world (say a single instance with 8 GPUs). THe problem is I cannot go and create a new process of rank 0 because it is already being used by the smddp process_group. I would just like to select the rank 0 process in the existing process group to test on. Is it possible to do so? Or must it be some distinct process_group from that which is being used for training?

**Comment by SkafteNicki** [comment]
I am not familiar on the `smddp` backend, but to call operations such as `torch.distributed.all_gather`, `torch.distributed.barrier` we need to define a process group which we want to call the operations on (by default the world). I therefore see no way around actually defining a new process group only containing rank 0.

To me it seems like the easier solution here, would be to refactor the code that runs only on a single rank into its own script that then can load in the trained model. Then that script can be run non-distributed.

**Comment by neel04** [comment]
I'm facing the same issue @SkafteNicki - with DDP, it just hangs until timeout:
```py
RuntimeError: NCCL communicator was aborted on rank 27.  Original reason for failure was: [Rank 27] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=430752, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1800826 milliseconds before timing out.
```
