### ISSUE TITLE
Implement Average() and Sum()

### ISSUE THREAD

**Issue by bishshoy** [PyTorchLightning/metrics#963]
## 🚀 Feature

Is an Average and Sum metric already implemented? I couldn't seem to find one. It would be great if it can be added to the existing API.

### Motivation

Often, we want to just observe the average of the loss or some other quantity over time. Most pytorch github repos implement something called an `AverageMeter()`, which is basically a class that keeps average of the quantities in track and prints them when called.

**Comment by SkafteNicki** [comment]
Hi @bishshoy,
We have a average and sum metric already implemented:
```python
from torchmetrics import SumMetric, MeanMetric
s = SumMetric()
s.update(1)
s.update(2)
print(s.compute()) # prints tensor(3.)
m = MeanMetric()
m.update(1)
m.update(2)
print(m.compute()) # prints tensor(1.5)
```
Docs can be found here: https://torchmetrics.readthedocs.io/en/stable/references/aggregation.html (for now, may change location since they are a bit hidden away)
Closing issue.
