### ISSUE TITLE
Allow Accuracy to return metric per class

### ISSUE THREAD

**Issue by SkafteNicki** [PyTorchLightning/metrics#99]
## 🚀 Feature

Implement the `average` argument like in Precision and Recall such that accuracy metric can return the metric per class label.

### Motivation

Sometimes it may be beneficially to look at the accuracy per label, especially when working with very unbalanced datasets

**Comment by arvindmuralie77** [comment]
Dear @SkafteNicki , can I work on this?

**Comment by SkafteNicki** [comment]
@arvindmuralie77 yes, I will assign you. Thanks for wanting to contribe :]
Please make sure that the feature follows the same pattern as with `precision`, `recall` ect. by adding an argument `average` which normally can take the values `'micro'`, `'macro'`, `'weighted'`, `'none'` and `None` where the two last corresponds to returning the score per class.

**Comment by arvindmuralie77** [comment]
Sure, will do. Thanks @SkafteNicki

**Comment by arvindmuralie77** [comment]
I was thinking of changing the parent class from `Metric` to `StatScores` in `Accuracy`. This way, I can use `tp`, `fp`, `tn`, and `fn` to calculate accuracy for all values of `average`. Would that be alright @SkafteNicki ?

**Comment by arvindmuralie77** [comment]
I was thinking of changing the parent class from `Metric` to `StatScores` in `Accuracy`. This way, I can use `tp`, `fp`, `tn`, and `fn` to calculate accuracy for all values of `average`. Would that be alright or should I try without changing the base class @SkafteNicki ?

**Comment by SkafteNicki** [comment]
@arvindmuralie77 Fine by me, that is basically also what I would do :]

**Comment by arvindmuralie77** [comment]
Hey @SkafteNicki , I have created a draft for this issue. When pytest for accuracy is run, 23 tests are failing out of 102 because the  mdmc_average parameter does not have default value. If it is set to `global` all test cases are passing. 
I think new test cases will have to be added since there are new parameters.
