### ISSUE TITLE
Could you implement Dice score as metric  

### ISSUE THREAD

**Issue by alqurri77** [PyTorchLightning/metrics#992]
I notice Dice score is implemented as functional, but it could not be used as metric (like accuracy metric example). Could you please implement Dice score as metric.

**Comment by Borda** [comment]
@alqurri77 good point. Are you interested in sending such PR?

**Comment by alqurri77** [comment]
Do you mean creating a pull request. I don't I think have enough background to do this.

**Comment by Borda** [comment]
> Do you mean creating a pull request. I don't I think have enough background to do this.

it is not hard, pls have look at [Quick Open-Source Contribution Guide](https://devblog.pytorchlightning.ai/quick-contribution-guide-86d977171b3a)

**Comment by MrShevan** [comment]
Hi, @Borda @alqurri77 !
If it is still unresolved, could you assign it to me?)
